### ISSUE TITLE
Parsing values in MoneyInput 

### ISSUE THREAD

**Issue by islam3zzat** [commercetools/ui-kit#1017]
**Describe the bug**
Different locals have different ways for formatting numbers to name 3 examples:
- Some locals use the `,` for thousands separation and `.` for fractions separation (e.g  `EN`),
- others the other way around (e.g `DE`), and others
- use ` ` for thousands separation and `.` for fractions separation (e.g `FR`).

Because of that, we had to put locale into consideration when parsing numbers.
To find out what are the throwaway and what is the fraction symbol based on the locale we used to format a random number **`9999.999`** with fractions (to get the fraction symbol) and more than 3 digits in the non-fraction part (to get the thousands symbol).
So that after formatting it can be for examle
- `"9,999.999"`
- `"9.999,999"`
- `"9 999.999"`
- `"9 999,999"`
Then we remove the number and split, the result would be for examle
- `[',', '.']`
- `['.', ',']`
- `[' ', '.']`
- `[' ', ',']`

From the output, we'll find out the `thousands symbol` (the first item) and the `fraction symbol` (the last item)
Then we remove the thousands separator and replace the fraction symbol with a `.`  from the number to be parsed (e.g **`12 345,67`)**
So that it'll be **`"12345.67"`**
Then parse the result to float  **`12345.67`.**
https://github.com/commercetools/ui-kit/blob/4d64e24f00335e3177aa6dabcab4bd8eb53f7571/src/components/inputs/money-input/money-input.js#L183

This worked fine until we found out that some locals have Exceptions to digit grouping and don't  show thousands separator for four-digits number 

https://en.wikipedia.org/wiki/Decimal_separator#Exceptions_to_digit_grouping

Which causes our solution to fail because the random number that we initially choose was 4-digits (9999.999 )and formatting it with this locale will result `"9999,999"` 
and after the removing the numbers and splitting, it'll be [","]
And when assigning the first item to the thousands separator and the second to the fractions separator we'll end up with.
thousands separator = "," 
fractions separator = undefined

**To Reproduce**
1. Switch to the `es-PE` locale
2. go to [Price details](https://mc.commercetools.com/test-with-big-data-44/products/7af8191b-cc75-4376-be73-4959f2bfe61f/variants/4/prices/0d8a5766-c0f9-41c9-86a4-10b970331075)
3. Choose the `EUR` currency
4. Enter `7070707` for the amount
3. keep focusing in and out

PS: the function `parseRawAmountToNumber` doesn't have any dependencies, meaning u can easily copy it and paste it in the console and experiment with the following examples
- parseRawAmountToNumber("1,77", "es") should output `1.77` but outputs `177`
- parseRawAmountToNumber("177.777", "es") should output `177777` but outputs `177.777`
- parseRawAmountToNumber("177 777", "es") should output `177777` but outputs `177`

**Expected behavior**
It should correctly parse the number
**Screenshots**
![Kapture 2019-08-22 at 13 47 43](https://user-images.githubusercontent.com/7680511/63512192-7a4d0900-c4e3-11e9-8756-c66a6170cb61.gif)

**Additional context**

**Comment by islam3zzat** [comment]
One possible easy solution would be to change the number that extracts the format symbols from `9999.999` to `9999.999` so that the non-fraction will not be just 4 digits.
```js
parseRawAmountToNumber = (rawAmount, locale) => {
  let throwaway;
  let separator;

  if (locale) {
    [throwaway, separator] = (99999.999) // we need any number that has more than 3 digits to show the thousand sepirator, and has fractions
      .toLocaleString(locale) // after this step (localizing it) it'll be either 9,999.999 or 9.999,999 based in the locale
      .replace(/9/g, '') // then we remove the number `9` to endup with `,.` or `.,`
      .split('')
      .map(symbol => (symbol === '.' ? '\\.' : symbol)); // here we escape the '.' to use it as regex
  } else {
    const lastDot = String(rawAmount).lastIndexOf('.');
    const lastComma = String(rawAmount).lastIndexOf(',');

    separator = lastComma > lastDot ? ',' : '.';
    throwaway = separator === '.' ? ',' : '\\.';
  }
  // The raw amount with only one sparator
  const normalizedAmount = String(rawAmount)
    .replace(new RegExp(`${throwaway}`, 'g'), '')
    .replace(separator, '.');

  return parseFloat(normalizedAmount, 10);
};
```
This will fix the Spanish locale problem, but I'm not sure if another locale has a similar issue with 5 digits.

**Comment by islam3zzat** [comment]
Other possible solution would be not to put the `thousands separator symbol` at all into consideration
And we just get the fraction symbol under the provided locale.

and at the end before parsing, instead of removing the `thousands separator symbol` we'll remove everything except for digits and `fraction separator symbol`.

```js
parseRawAmountToNumber = (rawAmount, locale) => {
  let fractionsSeparator;

  if (locale) {
    [fractionsSeparator] = (2.5) // we need any number with fractions, so that we know what is the fraction
      .toLocaleString(locale) // "symbol" for the provided symbol
      .replace(/\d/g, '') // then we remove the numbers and keep the "symbol"
      .split('')
      .map(symbol => (symbol === '.' ? '\\.' : symbol)); // here we escape the '.' to use it as regex
  } else {
    const lastDot = String(rawAmount).lastIndexOf('.');
    const lastComma = String(rawAmount).lastIndexOf(',');

    fractionsSeparator = lastComma > lastDot ? ',' : '.';
  }
  // The raw amount with only one sparator
  const normalizedAmount = String(rawAmount)
    .replace(new RegExp(`[^0-9${fractionsSeparator}]`, 'g'), '') // we just keep the numbers and the fraction symbol
    .replace(fractionsSeparator, '.'); // then we change whatever `fractionsSeparator` was to `.` so we can parse it as float

  return parseFloat(normalizedAmount, 10);
};
```

**Comment by montezume** [comment]
@islam3zzat can this be closed now then?

**Comment by islam3zzat** [comment]
Yup
/close
