### ISSUE TITLE
Localized Inputs Break When Value Is Null

### ISSUE THREAD

**Issue by montezume** [commercetools/ui-kit#1106]
#### Summary

`LocalizedTextInput`, `LocalizedMultilineTextInput`, `LocalizedMoneyInput` and `LocalizedRichTextInput` all crash when supplied with an undefined or null `value` prop.

I am not sure what the expected result would be, since we derive the `languages` from the `value` prop. So if `value` is undefined, we can't render any inputs as we don't know which language labels to use?

**Comment by islam3zzat** [comment]
We can either
- Add invariant that the value needs to be an object.
- Default to empty object.

If the PropTypes is enough we can close the issue, if not I'm leaning towards the first option.

**Comment by montezume** [comment]
What would we render when it's an empty object though? It would be an input without any inputs?

**Comment by islam3zzat** [comment]
if `selectedLanguage` was undefined
It'll also break `Cannot read property 'split' of undefined`.

**Comment by islam3zzat** [comment]
The special case about `value`, is that it's very normal to get a product for example with no description
But I can't think of any case where we don't have a language.

**Comment by montezume** [comment]
For me it would make sense in this case to allow null / empty values
```
  <Input value={null} languages=['en, 'de'] language="en" />
```

But in our care where the languages are derived from value, it does not make sense to me to allow null values.

**Comment by islam3zzat** [comment]
then in the localised inputs case, would the `invariant` make more sense?

**Comment by montezume** [comment]
invariant is a breaking change though, we had problems where it broke apps

**Comment by montezume** [comment]
If there was a visual case for a null "localizedinput" it would make more sense. 🤔

**Comment by islam3zzat** [comment]
The propType already says it's required, this should be fine for now.
what do u mean by "visual case"?

**Comment by montezume** [comment]
I mean if it was a state that we would want to visually represent with the input.

**Comment by montezume** [comment]
Another option we have would be to do something like this (example from `LocalizedTextInput`)

```js

const value = createLocalizedString(props.value);

```

Then it would not crash when we pass in invalid options. Might have performance implications though?

**Comment by islam3zzat** [comment]
> Might have performance implications though?

We'd only do this in the `docToFormValues` one time, so this shouldn't cause a problem.

**Comment by montezume** [comment]
@islam3zzat sorry I meant if we did this inside of the UI-Kit component.

**Comment by islam3zzat** [comment]
We can just provide it as a static function.
Then it's up to the user.

**Comment by montezume** [comment]
We do provide it as a static function 😉.

So should I close this then?

**Comment by islam3zzat** [comment]
Sorry for missing that.
I think this is enough.
