### ISSUE TITLE
RichTextInput (sometimes) has ghost pixel

### ISSUE THREAD

**Issue by montezume** [commercetools/ui-kit#1123]
#### Summary

Sometimes the `RichTextInput` has this weird ghost pixel that disappears on resize. 

![image (12)](https://user-images.githubusercontent.com/2425013/67273418-ab838e80-f4be-11e9-8b83-2d880962ddda.png)

**Comment by tdeekens** [comment]
Maybe something wrong int he markup generated?

**Comment by montezume** [comment]
Could be. The problem is I can't recreate it 😱

**Comment by tdeekens** [comment]
_slowly clicks the "Close and comment button_.

**Comment by montezume** [comment]
My best guess is that this was due to us using `output` instead of `div`. I'm curious to see if this reappears 🙏

**Comment by jonnybel** [comment]
Haven't been able to spot it. Closing until someone complains 👀
