### ISSUE TITLE
Add a component prop to RadioInput.Option that wraps its contents

### ISSUE THREAD

**Issue by dogayuksel** [commercetools/ui-kit#1136]
Adding a Tooltip around a single RadioInput.Option is not possible since RadioInput.Group expects RadioInput.Option to be a direct child.

Possibly adding a `component` prop to RadioInput.Option and wrapping its contents with that given component on render would provide more flexibility for such use cases.

`<RadioInput.Option component={<Tooltip />} />`

**Comment by tdeekens** [comment]
Thanks for creating the issue. I think it might be worth having a `components` prop so we call supply multiple, if needed, in the future. so `components={{Tooltip}}

**Comment by tdeekens** [comment]
The more generic naming also sounds legit. :)
