### ISSUE TITLE
add linkTo property on IconButton

### ISSUE THREAD

**Issue by YahiaElTai** [commercetools/ui-kit#1162]
I was working on the addresses panel on MC and I needed an icon button with a link and the original implementation was an `IconButton`  inside a `Link` and that added more code to a simple piece of functionality.
Please refer to the code snippet added to get a better view of the issue.

Adding a `linkTo` property on the `IconButton` will make things concise and more readable.

Note: if needed I can do a PR for it.

![image](https://user-images.githubusercontent.com/30247059/68288803-61390a80-0085-11ea-8316-005481d1a3a7.png)

**Comment by tdeekens** [comment]
For context. It's what the `SecondaryButton` has but also not the `PrimaryButton`. Maybe it makes sense to have it on all buttons. 

https://github.com/commercetools/ui-kit/blob/master/src/components/buttons/secondary-button/secondary-button.js#L89

**Comment by montezume** [comment]
I would probably go a different way and allow passing in an `as` prop

**Comment by tdeekens** [comment]
You mean `as={Link}`? Still we would have to pipe props? Also the `onClick` recomes uncalled-for with a `Link`. Maybe a `components`-prop is more apt? Like `components={{wrapper: Link}}`? I think with either solution `as` or `components` we quickly end up where we are now for consumers.

```jsx
const Wrapper = (props) => (
   <Link to="stairway">{props.children}</Link>
)

<IconButton as={Wrapper} />
<IconButton components={{wrapper: Wrapper}} />
```

is that what you had in mind?

**Comment by montezume** [comment]
@tdeekens check the emotion docs

https://emotion.sh/docs/styled

You can provide a shouldForwardProps, and just forward `to`.

Is that what you mean?

**Comment by montezume** [comment]
Actually this way we could completely remove "react-router-dom" as a peer dep 🤔

**Comment by tdeekens** [comment]
That's actually nice yeah. Just kind of noticed that `as` and `components` are like the same thing in two different APIs kind of. `components.as` feels like the big scalable brother of `as` where you can add more over time. After all, feels like `linkTo` should go away in favour of `as` and us being able to remove the peer dep.

**Comment by montezume** [comment]
I think `as` is better for components that follow(ish) the Single Element Pattern. Obviously things like Tooltips and RichTextInputs can't follow that pattern. But for Buttons, 'as' is nice. components feels weird because the button should only have one component.

**Comment by tdeekens** [comment]
Yeah in that it communicates a restriction nicely.

**Comment by montezume** [comment]
We can start by supporting both, and deprecate `linkTo` 🤔

**Comment by tdeekens** [comment]
Yau. Sounds decent.

**Comment by emmenko** [comment]
Just for me to understand: instead of using onClick and manually navigate, you want to pass the location directly, am I correct?

**Comment by tdeekens** [comment]
It's not just onClick. If you have onClick with a button stuff like `cmd+click` won't work. In that it breaks the web in a way.

**Comment by emmenko** [comment]
Right, thanks for clarifying 👌
