### ISSUE TITLE
How are you guys able to build this lib properly with styled components and SSR?

### ISSUE THREAD

**Issue by vongohren** [commercetools/ui-kit#1209]
**Is your feature request related to a problem? Please describe.**
Im trying to build a library like this, with styled components! Loaded with SSR.

**Describe the solution you'd like**
And insight to how to build something like this, in this repo: https://github.com/vongohren/fouc-example.

**Describe alternatives you've considered**
Its not relative, but looking at emotion-js and styled components as a base.

**Comment by emmenko** [comment]
Hey, we use emotion which has built-in SSR support.

Have you checked this out, if you're using next.js? https://emotion.sh/docs/ssr#nextjs

**Comment by vongohren** [comment]
@emmenko hi, yes sorry for the copy paste, I have been a bit desperate lately for figuring it out. But this repo also has a emotion component in it, but that doc does not really convey what emotion is saying in this issue, about using emotion for SSR: https://github.com/emotion-js/emotion/issues/1516

**Comment by ranzolinrafa** [comment]
Hello! @vongohren  Did you got any solution for your issue? I'm getting stuck in the same problem in generating build for my ui lib to use in Next.JS.

@emotion/react: 11.1.4
@emotion/babel-plugin: 11.1.2

**Comment by vongohren** [comment]
@ranzolinrafa I moved away from styled components and did emotion js, as it worked out of the box
