### ISSUE TITLE
PropTypes warning when providing an empty string to `TextDetail`

### ISSUE THREAD

**Issue by ahmehri** [commercetools/ui-kit#1212]
**Describe the bug**
When providing an empty string `''` to `TextDetail` component, it will result in a PropTypes warning.

```
Warning: Failed prop type: The prop `intlMessage` is marked as required in `TextDetail`, but its value is `undefined`.
```

This is because of the check done here.

https://github.com/commercetools/ui-kit/blob/860410698e38c0934fb28ba47138a25aaf15d073/src/components/typography/text/text.js#L266

**To Reproduce**

https://codesandbox.io/s/exciting-lehmann-sgpgt?expanddevtools=1&fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
There should not be a warning when providing an empty string.

**Comment by tdeekens** [comment]
True that seems like a catch of it being coerced to a boolean. Would you open up a PR?

**Comment by ahmehri** [comment]
Yes, I will open a PR 👍
