### ISSUE TITLE
Improve accessibility of CollapsiblePanel

### ISSUE THREAD

**Issue by jonnybel** [commercetools/ui-kit#1263]
The `CollapsiblePanel` component [has been reported](https://github.com/commercetools/merchant-center-frontend/pull/8383/files#r379316051) to not being accessible (no aria labels) and hard to test because of its DOM structure: it should be easier to select the component that represents the content of a given header, for testing purposes.

My suggestion for fixing the `a11y`:
* We should use `aria-hidden` and `aria-expanded` for the 2 states.
* Ensure that the Header behaves like a `button`, being focusable and triggerable from the keyboard.
* We could add an `id` to the content of the panel and associate it with `aria-controls` on the header button.

For the DOM structure, it has been suggested to make the content a child of the header, but I would try to avoid this, because collapsibles are usually just plain buttons which show/hide another element regardless of its location in the DOM (almost always its next direct sibling).

A couple of sources for helping with this:
* https://inclusive-components.design/collapsible-sections/
* https://accessibility.huit.harvard.edu/%E2%9C%8E-practice-expandable-sections

**Comment by tdeekens** [comment]
Thanks. For summarizing things here so quickly!

1. `aria-hidden` und `aria-expanded` would already be nice. Won't help much with testability however I think.
2. Having for instance [aria-labelledby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute) or something else like you suggested with `id` and `aria-controls` would help greatly.
3. UI-Kit could also export custom react-testing-library selectors which integrate with its components on a more higher level. This way we could encapsulate their component and it's testability together (💯). Silly ideas would be `queryCollapsibleByTitle` for instance. Any app of app-kit would then consume these and extend its own selectors with UI-Kit's.

**Comment by jonnybel** [comment]
Opened a PR for this ⬆️ 

Regarding your 3rd point, I will open a separate issue for that idea once we close this one 🙂

**Comment by tdeekens** [comment]
Awesome 💯. Thanks a lot!
