### ISSUE TITLE
Add ability for hidden input labels to be able to target inputs without visual labels

### ISSUE THREAD

**Issue by tdeekens** [commercetools/ui-kit#1269]
Our current setup of inputs and labels and their combination in labels works great. However, at times we do not have the visual space to place a label next to the input. 

This case here

<img width="288" alt="CleanShot 2020-02-28 at 15 53 39@2x" src="https://user-images.githubusercontent.com/1877073/75558775-9e654600-5a42-11ea-8dd9-fcd841732508.png">

Is an input without an label. The same applied to

<img width="385" alt="CleanShot 2020-02-28 at 15 54 57@2x" src="https://user-images.githubusercontent.com/1877073/75558817-b1781600-5a42-11ea-8a3b-66d6baa39190.png">

This is not ideal from an accessibility perspective and also impacts how we can test these inputs. Without a label inputs are hard to target in our rtl and cypress testing setup.

As a result I propose that:

1. The <Name>Field receive an `isLabelHidden` (or named differently) to hide labels visually but have them present in the DOM
2. Add a `isVisible` to our `Label` component

This could allow us to render a invisible label next to an input while targeting it in testing.

Note that this is just an idea and I am myself not really sure if the approach is right.

**Comment by jonnybel** [comment]
Thanks for opening this issue.

I understand the problem and I agree with the concept of adding a hidden label to make tests easier (as well as improving a11y while we're at it).

Adding an `isLabelHidden` prop to the `Fields` could actually also be useful to a few use cases (which we've already seen) where a developer wants to take advantage of the validation logic that is built-in for `Fields` but not `Inputs`, while not wanting to render the `Label`.

I think my approach would be exporting an `HiddenAccessibleLabel`, or even a `HiddenAccessibleComponent` which you could decide what element to render with an `as` prop, and it would just add the necessary CSS to make it [hidden but screen-readable](https://webaim.org/techniques/css/invisiblecontent/#techniques). Then this component would be used by the Field components as well when you set the `isLabelHidden` prop.

**Comment by tdeekens** [comment]
Thanks for understanding the issue. This is an interesting approach. Having a AccessibleLabel and a HiddenAccessibleLabel could be a good separation. Question only would be how much they differ after all apart form some CSS.  Maybe the HiddenAccessibleLabel uses the AccessibleLabel below? Is that what you mean? Sorry, if this is already too implementation specific.

**Comment by jonnybel** [comment]
Actually, I don't think we need to have an "AccessibleLabel" component. A `label` element is already accessible as is, and one should use our existing `Label` component to follow the design system. An `AccessibleLabel` would simply be a native, unstyled HTML `label`. Moreover, we should avoid exporting components that don't follow the design system.

I only see meaningful value having a `HiddenAccessible(Label|Component)`, which doesn't actually need to follow the design-system styles because it's not visible to the users, but it's valuable for a11y and testing reasons.

**Comment by tdeekens** [comment]
Makes sense. Thanks. Let me know if I can help somehow.
