### ISSUE TITLE
Bug: DateField fails to render

### ISSUE THREAD

**Issue by davifantasia** [commercetools/ui-kit#1332]
**Describe the bug**
When trying to use the [DateField](https://www.npmjs.com/package/@commercetools-uikit/date-field), I get this error:

```
/Users/aoluyinka/commercetools/commercetools-docs-kit/node_modules/@commercetools-uikit/date-input/dist/date-input.esm.js
Module not found: Error: Can't resolve 'react-intl' in '/Users/aoluyinka/commercetools/commercetools-docs-kit/node_modules/@commercetools-uikit/date-input/dist'
```

**To Reproduce**

Install DateField as a dependency in `package.json`

```
...
"dependencies": {
  "@commercetools-uikit/date-field": "10.18.4"
}
...
```

Import in and use in React component

```
import DateField from '@commercetools-uikit/date-field';

...
       <DateField
          title="Release Date"
          value="2018-10-30"
          onChange={(event) => console.log(event.target.value)}
        />
...
```

**Expected behavior**
Should render a date as described here - https://uikit.commercetools.com/?path=/story/components-fields--datefield

**Comment by emmenko** [comment]
The error is pretty clear: the package requires you to install `react-intl`, which is a peer dependency of the package

**Comment by davifantasia** [comment]
> The error is pretty clear: the package requires you to install `react-intl`, which is a peer dependency of the package

I found it unusable - the dependency needs to be documented in the package.

**Comment by davifantasia** [comment]
> The error is pretty clear: the package requires you to install `react-intl`, which is a peer dependency of the package

Question about usability - shouldn't the package include the dependency itself?
