### ISSUE TITLE
Modal component?

### ISSUE THREAD

**Issue by shanly-suepaul** [commercetools/ui-kit#1333]
**Is your feature request related to a problem? Please describe.**
I often see modal dialogs for important confirmations in MC eg: 

![image](https://user-images.githubusercontent.com/858736/80776679-f0a11100-8b30-11ea-8ad1-6f39ffeec4de.png)

This isn't available in the current UI Kit as far as I can see.

**Describe the solution you'd like**
Can you add a modal component that can have arbitrary children?

**Describe alternatives you've considered**
I've considered just using my own modal library with the Card component from UI Kit. However, that will overlay the entire page, when I really only want it to overlay the main content section. See this example from the MC: 
![image](https://user-images.githubusercontent.com/858736/80776856-59888900-8b31-11ea-83fb-3b56b920e71a.png)

**Comment by emmenko** [comment]
Hi, Dialog components and Modal pages are published to a different package and the code live in the app-kit repository.

See UI components section in the custom apps docs. For example: https://docs.commercetools.com/custom-applications/components/info-dialog

## Background

The uikit library only contains low-level primitive components. Other UI components such a dialogs, modal pages etc are more specific to custom applications and therefore they live in the appkit repository.
I suppose we need to document this better.

In general (and for the future) we intend to have 3 levels of abstractions:
- primitive components: buttons, inputs, etc
- application components: dialogs, modals, etc
- business components: product component, a product reference search component, etc

**Comment by shanly-suepaul** [comment]
Thanks, sorry about that.
