### ISSUE TITLE
New DataTable footer not sticky

### ISSUE THREAD

**Issue by fuchodeveloper** [commercetools/ui-kit#1410]
**Describe the bug**
While implementing the new `DataTable` component, I observed that the footer prop is not sticky.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://codesandbox.io/s/data-table-demo-7869876fdz-10cqi 
2. On the browser window by the right
3. Scroll through the table content to see the table footer
4. Notice that the table header is sticky, but the footer is not sticky instead it scrolls with the rest of the table body.

**Expected behavior**
Table footer should be sticky just like the header is when a maximum height is applied on the data table.

**Additional context**
In the [docs](https://uikit.commercetools.com/?path=/story/components-table-new--datatable), both the `DataTable` header and footer are sticky when the table `maxHeight` property is set to a number that forces the table to display fewer content.

**Comment by jonnybel** [comment]
Hi!

The sticky footer behaviour was added in version `10.23.0` but your example is using `10.22.0`.
See: https://github.com/commercetools/ui-kit/releases/tag/%40commercetools-uikit%2Fdata-table%4010.23.0

Simply updating to `10.23.0` solves your problem 🙂

**Comment by fuchodeveloper** [comment]
Thanks, @jonnybel.
I can confirm that the sticky footer works with version `10.23.0`. I'll be closing this issue.
Thanks 🙂
