### ISSUE TITLE
User needs to scroll horizontally to see the rest of the DataTable's footer.

### ISSUE THREAD

**Issue by islam3zzat** [commercetools/ui-kit#1417]
**Describe the bug**
When the Datatable has many columns and its footer has content on both ends (e.g at the left end of the footer there is info about page, and on the right end there are the prev/next action buttons), the user has to scroll horizontally find the action buttons

**To Reproduce**

1. Go to the provided sandbox link
2. Scroll down to the footer area
3. You'll have to scroll horizontally to reach the prev/next action buttons.

https://codesandbox.io/s/data-table-demo-7869876fdz-kg7fl

**Expected behavior**
The footer should be fully displayed without needing to scroll.

**Screenshots**

**Additional context**
If we render the footer separately, we'll not have this issue as demonstrated in the example sandbox.

**Comment by jonnybel** [comment]
Thanks for creating an Issue for this problem.

While we work on fixing this, I would advise you to render the footer as a normal div on the bottom right after the table...
