### ISSUE TITLE
improve how ContentNotification handles its children

### ISSUE THREAD

**Issue by YahiaElTai** [commercetools/ui-kit#1476]
**Describe the bug**
`ContentNotification` uses `display:flex` for its children and that sometimes desirable but could also creates issues in other cases where for example: when displaying 2 HTML text elements as one inline paragraph

**Suggested solution**
One solution that comes to mind immediately is to add support for `display: block`

**Screenshots**
This screenshot shows how the "customer support" link is being displayed with `display: flex`
![image](https://user-images.githubusercontent.com/30247059/89981781-cce38000-dc74-11ea-91a8-d410d8fcf749.png)

This screenshot shows how the "customer support" link is being displayed when wrapping the 2 HTML elements in a container div (so the `ContentNotification` treat it as HTML element), so as you can see adding a wrapping container solves the issue but it might be helpful to have this handled by the uikit component itself. UiKit components should not enforce any layout on their children as I understand.
![image](https://user-images.githubusercontent.com/30247059/89981979-264baf00-dc75-11ea-8c7a-642ee59bc020.png)

**Comment by jonnybel** [comment]
> UiKit components should not enforce any layout on their children as I understand

I agree, except for the obvious layout components, which isn't the case of this one.

The only good way I think we could solve this is by adding a prop like `containerType` which accepts the values `flex` and `block`, with the default being `flex` so that we won't be breaking any existing layouts.

**Comment by YahiaElTai** [comment]
> > UiKit components should not enforce any layout on their children as I understand
> 
> I agree, except for the obvious layout components, which isn't the case of this one.
> 
> The only good way I think we could solve this is by adding a prop like `containerType` which accepts the values `flex` and `block`, with the default being `flex` so that we won't be breaking any existing layouts.

Sounds good to me! 🚀

**Comment by YahiaElTai** [comment]
@commercetools/shield-team @tdeekens any feedback on the proposed solution?

**Comment by tdeekens** [comment]
I would have liked to alternate between `props` so `intlMessage` does what we do now. `children` gives control. Then the consumer can use anything (e.g. a `Spacing`). 

That would however be breaking I assume.

I wonder if anybody wants to current behaviour/layout?

**Comment by YahiaElTai** [comment]
> I would have liked to alternate between `props` so `intlMessage` does what we do now. `children` gives control. Then the consumer can use anything (e.g. a `Spacing`).
> 
> That would however be breaking I assume.
> 
> I wonder if anybody wants to current behaviour/layout?

That would be nice but as you said it would be a breaking change.

**Comment by jonnybel** [comment]
Is this considered fixed by #1501 ?

**Comment by tdeekens** [comment]
Yes, I think so. Otherwise it can be re-opened. Sorry for not cleaning up.
