### ISSUE TITLE
Cannot find module '@emotion/styled-base'

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#1491]
**Describe the bug**
Installing latest dependencies causes build/lint errors.

```
Cannot find module '@emotion/styled-base' from 'node_modules/@commercetools-uikit/accessible-button/dist/accessible-button.cjs.js'
```

<img width="661" alt="image" src="https://user-images.githubusercontent.com/1110551/90223225-f2f05800-de0d-11ea-8992-161115a605df.png">

**To Reproduce**
https://github.com/commercetools/merchant-center-application-kit/pull/1673/checks?check_run_id=983630152

**Expected behavior**
The `@emotion/styled-base` is not a peer dependency and shouldn't be required to be installed by consumers.

**Screenshots**
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/1110551/90223092-b3c20700-de0d-11ea-84a6-678c4930475d.png">

**Additional context**
Maybe something related to this?
https://github.com/commercetools/ui-kit/blob/2db4063679813da5929b92e64a75582a8bc5e0bf/rollup.config.js#L38-L40

**Comment by alochowski** [comment]
Hi,
unfortunately, I have still the same problem with this module during production build, I've got:
`Module not found: Error: Can't resolve '@emotion/styled-base' in '/app/node_modules/@commercetools-uikit/accessible-button/dist'`

is there a chance to fix this somehow?

**Comment by emmenko** [comment]
Which versions of the uikit packages are you using?

**Comment by alochowski** [comment]
I'm using several packages from uikit, most of them are in version `10.30.1`

**Comment by emmenko** [comment]
This issue with emotion was fixed in version `10.30.1` (https://github.com/commercetools/ui-kit/pull/1483). Please make sure that all your packages are on the latest version.

**Comment by alochowski** [comment]
Here is my dependencies list for uikit :
```
    "@commercetools-uikit/card": "10.30.1",
    "@commercetools-uikit/collapsible-panel": "10.30.1",
    "@commercetools-uikit/data-table": "10.30.1",
    "@commercetools-uikit/flat-button": "10.30.1",
    "@commercetools-uikit/grid": "10.30.1",
    "@commercetools-uikit/icons": "10.30.1",
    "@commercetools-uikit/label": "10.30.1",
    "@commercetools-uikit/link-button": "10.30.1",
    "@commercetools-uikit/multiline-text-field": "10.30.1",
    "@commercetools-uikit/select-field": "10.31.0",
    "@commercetools-uikit/spacings": "10.18.7",
    "@commercetools-uikit/spacings-inset": "10.30.1",
    "@commercetools-uikit/spacings-stack": "10.30.1",
    "@commercetools-uikit/text": "10.30.1",
    "@commercetools-uikit/text-field": "10.30.1",
    "@commercetools-uikit/text-input": "10.30.1",
```

**Comment by emmenko** [comment]
I think you should remove `"@commercetools-uikit/spacings": "10.18.7",`

**Comment by emmenko** [comment]
Hmm actually that was also included there...

**Comment by emmenko** [comment]
But in general if you use the single `spacings` packages, you probably don't need the `spacings` package preset

**Comment by emmenko** [comment]
Have you tried to remove your `node_modules` and e.g. `yarn.lock` and re-install everything again? That helps sometimes 😅

**Comment by alochowski** [comment]
You are right, I had old package for `spacings` and new one for single spacings packages.
I removed old one and switched to new components. I've re-installed everything again and I still have got :
`Module not found: Error: Can't resolve '@emotion/styled-base' in '/app/node_modules/@commercetools-uikit/accessible-button/dist'` when I execute command: `NODE_ENV=production /app/node_modules/.bin/mc-scripts build`

Maybe there is no a problem with uikit dependencies but with `@commercetools-frontend`?

**Comment by emmenko** [comment]
Can you execute `yarn why @emotion/styled-base` and paste the output here?

**Comment by alochowski** [comment]
if I'm not wrong, e.g. package `@commercetools-uikit/collapsible-panel` also still using `@commercetools-uikit/spacings@10.18.7` as a dependency.

**Comment by alochowski** [comment]
```
yarn why @emotion/styled-base
yarn why v1.21.1
[1/4] Why do we have the module "@emotion/styled-base"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@emotion/styled-base@10.0.31"
info Reasons this module exists
   - "@commercetools-frontend#application-shell" depends on it
   - Hoisted from "@commercetools-frontend#application-shell#@emotion#styled-base"
   - Hoisted from "@commercetools-frontend#application-components#@emotion#styled#@emotion#styled-base"
Done in 0.85s.
```

**Comment by alochowski** [comment]
I'm using `"@commercetools-frontend/application-shell": "16.15.6",` should I upgrade this package?

**Comment by emmenko** [comment]
Ah yes I was looking into that as well. Please update the `@commercetools-frontend/` packages as well, so they use the correct uikit deps.

**Comment by alochowski** [comment]
Ok, now works. :+1:  
Solution for this was upgrade version of `@commercetools-frontend`
Thanks a lot for your help.

**Comment by emmenko** [comment]
Nice, glad we got this solved! 🙌
