### ISSUE TITLE
Add Image to Card component

### ISSUE THREAD

**Issue by fuchodeveloper** [commercetools/ui-kit#1514]
**Is your feature request related to a problem? Please describe.**
Currently, there is no first-class support for adding an image to the Card component.

**Describe the solution you'd like**
A more seamless way to add an image to the Card component with minimal custom styling. There are a few places on the MC which already implement this but they require custom styles which would result in possible inconsistencies across the app.

**Describe alternatives you've considered**
Writing custom styles using the current Card component

**Additional context**
An example from Bootstrap website - https://getbootstrap.com/docs/4.0/components/card/#example

![image-card](https://user-images.githubusercontent.com/22713293/90647054-d00bdc80-e22f-11ea-81de-fe5d59aed0fb.png)

**Comment by mariabarrena** [comment]
Just FYI, displaying jpgs or pngs in the MC (anything besides svgs) is not something we are starting to pursue. The banner for the user research program was a one time only case and it is 99% probable we will never do that again. If you guys want to add it to the component anyway, just have in mind there are no specs from the UX/UI team in regards of placement of images and sizes of pictures for this component for every single use case for now so I would put this on hold until we really have a need for it again (if any).

**Comment by tdeekens** [comment]
Thanks for opening and thanks for sharing. If we don't expect it to be needed again I am fine with not implementing it and focussing on other things. However, a card doesn't only have to hold an image in the top maybe. Could be text, SVG or anything. In case that's also not needed let's not focus on it. We just noticed that we introduce custom styling internally which we try to avoid and wanted to raise this here. Even if we close this for now we have a trail of information.
