### ISSUE TITLE
pagination on a data table

### ISSUE THREAD

**Issue by ct-jenny** [commercetools/ui-kit#1547]
I'm creating a custom application for our application and i would like to know if there's any solution to have pagination on a datatable?

If this is currently not possible, please let us know if you need further information on use case on this. 

Thank you and kind regards,
Jenny

**Comment by anilkk** [comment]
@ct-jenny: We don't have pagination on **datatable** now.  Can you please provide more information on the use case?

**Comment by ct-jenny** [comment]
I am currently asking the customer for more information and will update here as soon as I get more info in [https://jira.commercetools.com/browse/SUPPORT-9918]

**Comment by emmenko** [comment]
@ct-jenny no links to internal support issues please!!

**Comment by emmenko** [comment]
Closing, as we now have published a Pagination component: https://github.com/commercetools/ui-kit/tree/master/packages/components/pagination
