### ISSUE TITLE
Suggestion to deprecate the `hasUnderline` prop on `Link`

### ISSUE THREAD

**Issue by tdeekens** [commercetools/ui-kit#1548]
# Summary

The `Link` component allows to disable the underline via the `hasUnderline` property. Usually links around the web have underlines. As a result, after talking to a @Shecki, we suggest to restrict the usage of `hasUnderline`.

# Description

The `hasUnderline` option is only used once internally. @Shecki recommended that all `Link`s should always have an underline and this option does not need to exist.

As a result, we propose a deprecation process, of undetermined length until the next major release, of the `hasUnderline` prop.

This means we:

1. Remove the Knob from the story book
2. Add a comment to the readme that the property is deprecated
3. Keep track of the change to remove it in a major release issue

**Comment by tdeekens** [comment]
An alternative would be that the `Link` accepts an `icon` prop which hides the underline. It in turn out also allow us to get rid of the `FlatButton` which is often only used to combine icon and link.

**Comment by mmaltsev-ct** [comment]
Done in #1826. Hence, closing this issue.
