### ISSUE TITLE
Drop TimeRangePicker

### ISSUE THREAD

**Issue by dferber90** [commercetools/ui-kit#158]
The ui-kit currently offers a component called [`TimeRangePicker`](https://uikit.commercetools.com/?selectedKind=TimeRangePicker&selectedStory=TimeRangePicker&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel) which looks like this:

![image](https://user-images.githubusercontent.com/1765075/46916120-8bb9b080-cfb6-11e8-8a9c-05b7cc5857dc.png)

I would suggest to remove this component from ui-kit as it can be built pretty easily on top of existing ui-kit components, and it is only used once in the MC.

**Comment by montezume** [comment]
Closed in #305
