### ISSUE TITLE
Rethink export and consumption of css vars

### ISSUE THREAD

**Issue by montezume** [commercetools/ui-kit#170]
#### Problem

How we export and consume css variables leaves a bit to be desired...

#### Current situation

```css
@import '@commercetools-frontend/ui-kit/materials/colors/base-colors.mod.css';
```

#### Possible way forward

`postcss-custom-media` has introduced `importFrom` and exportTo` functionality.

For example, for `base-colors.mod.css` (which is already generated from JS), we could instead have these generated to a json file, and then use importFrom to consume them. 

I would propose doing a bit of research into this and making a spike out of it.

**Comment by tdeekens** [comment]
Nice idea. I've seen that somewhere that colors and variables in general where exported as JSON, JS and CSS variables.

**Comment by montezume** [comment]
@tdeekens yeah would be great to give consumers more options

**Comment by dferber90** [comment]
Having our tokens as JSON/JS is great for ui-kit itself as well. It is possible to customize `react-select` with CSS-in-JS, but we need to fall back to overwriting its styles in CSS right now as we don't have access to the design tokens from JS!

**Comment by emmenko** [comment]
Who would like to do a spike on this? Should we plan something?

**Comment by dferber90** [comment]
@montezume is on it

**Comment by dferber90** [comment]
@montezume should we close this one?

**Comment by montezume** [comment]
@dferber90 I think we have done everything. The only thing we didn't deal with is exporting the [media queries](https://github.com/commercetools/ui-kit/blob/master/materials/media-queries.mod.css). There is a similar way with [postcss-custom-media](https://github.com/postcss/postcss-custom-media) but I'm not sure if it's worth the trouble. Would be nice to remove that need for V6 that @emmenko found though.
