### ISSUE TITLE
Html label element should not use htmlFor

### ISSUE THREAD

**Issue by harm-meijer** [commercetools/ui-kit#1823]
In html the id attribute should be unique in the DOM so React component should never use id html attribute since a React component should not know about all the id's in the DOM, it should only be concerned with the part of the DOM it is rendering. If a React component sets id html attribute on an element and is rendered multiple times in the document it will make the html invalid. This will force the browser to go in quirks mode and even though nothing will break now the name "quirks mode" does not indicate a predictable outcome.

There is no need to use [htmlFor](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#attr-for) because you can place input elements [as children](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) of the label but that is not how FieldLabel works.

**Comment by emmenko** [comment]
Hi, thanks for the feedback.

I'm a bit confused though about what you are trying to say. Are you suggesting that `<FieldLabel>` should use children and render the e.g. input within the `<label>` element?

Also in regards to the `id`, the consumer usually should take care of providing unique IDs. However, the uikit `<Field*>` components automatically generate a unique ID if none is provided: https://github.com/commercetools/ui-kit/blob/6514a11a7a11ff26e4734e93aad4fa358343cb68/packages/components/fields/text-field/src/text-field.js#L163

Please correct me if I'm missing the point here. Thanks

**Comment by harm-meijer** [comment]
Hi @emmenko, thank you for your reply I am saying that React components should never render html elements with an html id attribute (they can have an id prop used by React that isn't rendered) because it goes against component design for a component to know how to generate a unique that is unique to the entire DOM. Sure you can generate a unique id but what if other packages do the same, how can you guarantee the id is unique and why would you want to do such a thing anyway is it's not something a component should do?

Html specifications are such that id attribute is not needed as it provides alternatives and in React you can use refs if you need to reference an html element. You would be hard pressed to find any React documentation that will render an element with an html id attribute (there is none because it's wrong).

What I was suggesting is to not rely on the id of another element when creating a label and have the element be a child of label as documented in the [mdn article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) (`Alternatively, you can nest the <input> directly inside the <label>, in which case the for and id attributes are not needed because the association is implicit`). 

I am trying to put a [SelectInput](https://www.npmjs.com/package/@commercetools-uikit/select-input) in a label and thought FieldLabel was the thing to use but I guess it's not.

Anyway; label is working for me and the id thing is just a suggestion, vue uses html id attributes everywhere in their documentation and to me that shows a lack of understanding what a component that renders to DOM is supposed to do.

**Comment by emmenko** [comment]
> I am trying to put a SelectInput in a label and thought FieldLabel was the thing to use but I guess it's not.

If you use inputs with the label, you should use the `<*Field>` components. For example in your case it would be `<SelectField>`: https://uikit.commercetools.com/?path=/story/components-fields-selectfields--selectfield

In the field components the ID is automatically defined if none is provided.

---

Regarding the general argument about providing IDs or not, we support that for a11y purposes. For instance to "link" the label and the input element.
Nesting the input inside the label makes it harder to style the elements, especially for complex fields and interactions.

The uikit is opinionated about certain things on purpose, as it allows us to provide components with reasonable defaults and of course to adhere to our design system and guidelines.

Having said that, I really do appreciate your valuable input, especially around such non-obvious things. We are also happy to get any feedback and ideas about improving our components, accessibility, API design, etc. 🙏

**Comment by harm-meijer** [comment]
@emmenko I understand that removing the id attribute is nearly impossible as a lot of code may depend on it so probably just leave it. Thank you for your input.

**Comment by harm-meijer** [comment]
Forgot to close the issue, it is not worth the effort to not depend on html element id at this moment.
