### ISSUE TITLE
Change PageNavigator page number programmatically

### ISSUE THREAD

**Issue by Tormand** [commercetools/ui-kit#1838]
When changing the page number on PageNavigator programmatically, it dosent update the viewed page number 

**To Reproduce**
`<Pagination perPageRange="m" perPage={perPage} totalItems={totalOrders} page={page} onPageChange={pageChange} onPerPageChange={perPageChange} />`

In another function, change 'page' to another value.

**Comment by adnasa** [comment]
Hey @MartinTormandKruso , thank you for your message.

Can you elaborate this?
> In another function, change 'page' to another value.

If we look at the storybook, the pagination reflects the page change when you navigate between pages
https://uikit.commercetools.com/?path=/story/components-pagination--pagination

so I'm not sure how to reproduce your problem otherwise. what does  `pageChange` in `onPageChange={pageChange}` do exactly?

Thanks

**Comment by MartinTormandKruso** [comment]
Hey @adnasa 

Yeah, I can see my initial post is a bit confusing.

Say I have a DataTable with the Pagination and I also have a filter option(i.e. filter orders by date). Then when I'm on page 4 and change the date filter, I will then make a new call for orders filtered by the new date and change `Page` to page 1. But when I do that in the call function it dosen't change the page number that the user sees.

My `pageChange` does the following:
```
const pageChange = (pageNumber) => {
	page = pageNumber
	getAllOrders()
}
```
In `getAllOrders()` I fetch orders with different filters:
```
const getAllOrders = () => {
	asyncDispatch(actions.fetchAllOrders(perPage, page, textSearch, status, shippingMethod, shippingCountry, store, paymentStatus, date))
			.then((result) => {
				dispatch({ type: 'ok', payload: result })
				setTotalOrders(result.total)
				setOrders(orders(result.results)
			})
			.catch((error) => {
				dispatch({ type: 'error', payload: error })
				showApiErrorNotification({ errors: error })
			})
	}
```

Then I have a SelectInput where you can filter by dates(7 days back, 1 month back etc):
```
<SelectInput
	options={dates}
	value={date}
	onChange={(e) => {
		date = e.target.value
		page = 1
		getAllOrders()
	}}
/>
```
When I set the page to 1, it dosent show in the Pagination component, but it does get orders from the correct page.

My page variable is set outside the React function:
```
var perPage = 20
var page = 1

const ViewOrders = (props) => {
	const asyncDispatch = useAsyncDispatch()
	const showApiErrorNotification = useShowApiErrorNotification()
	const [state, dispatch] = useReducer(reducer, initialState)
	const [orders, setOrders] = useState([])
	const [totalOrders, setTotalOrders] = useState(0)
	...Rest of the React function
}
```
I've also tried to set up the page as a React state, like this:
`const [page, setPage] = useState(1)`

But that dosen't work either.

**Comment by adnasa** [comment]
with the following...

```jsx
var perPage = 20
var page = 1
```

this won't work because they are global variables and mutation on them won't cause a re-render (where the component will pick up the updated value) when the value changes.

using `useState()` is the right approach, and we should expect that the pagination picks up the new value.
you'll just to make sure that you forward the value of `page` and `perPage` into `getAllOrders()`, e.g `getAllOrders(page, perPage)`

do you unmount the component after/while you are fetching the orders?
this info might point me in the right direction as to finding the root to the problem.

**Comment by adnasa** [comment]
I gave this a spin, and I can not reproduce it
https://codesandbox.io/s/condescending-sky-8gi1q?file=/src/App.js

did you update your `pageChange` function after trying `useState()`?

**Comment by MartinTormandKruso** [comment]
I forked your codesandbox to give an example of what I've tried when trying `useState()`:
[https://codesandbox.io/s/patient-wind-5ffem](https://codesandbox.io/s/patient-wind-5ffem)

Bascially setting the page to 1, when changing the perPageRange. But it dosen't seem to work?

**Comment by emmenko** [comment]
Hi, at the moment the `page` prop that you pass to the component is only used as the "initial" state value, therefore changing it won't change the behavior of the internal pagination state.

https://github.com/commercetools/ui-kit/blob/d91814718a7e569f0a3555dd2e3f0fa0371c60b8/packages/components/pagination/src/page-navigator/page-navigator.js#L17

This is what is causing this issue. I don't see an issue of updating the internal `page` state according to the prop but we need to check and think about if there might be potential side effects.

Thanks

**Comment by adnasa** [comment]
hey @Tormand 
we released v11.3.0 some time ago where we addressed your concern
https://github.com/commercetools/ui-kit/pull/1841

will you have a look, migrate and come back to us with feedback?
Thanks in advance

**Comment by Tormand** [comment]
Hej @adnasa 
It works perfect! Thank you very much!

**Comment by adnasa** [comment]
Awesome!

hope to hear from you soon again.
