### ISSUE TITLE
<LinkButton /> deprecation is not documented

### ISSUE THREAD

**Issue by ahmehri** [commercetools/ui-kit#1848]
**Describe the bug**
`<LinkButton />` deprecation is not documented, and no alternative is proposed.

**To Reproduce**

1. Go to https://uikit.commercetools.com/?path=/story/components-buttons--linkbutton

**Expected behavior**
The deprecation is not documented. I was aware of it via a console warning and couldn't know the alternative until checking https://github.com/commercetools/ui-kit/pull/1169.

**Screenshots**

<img width="599" alt="Screenshot 2021-04-06 at 12 35 14" src="https://user-images.githubusercontent.com/3668245/113699708-37e73880-96d6-11eb-88a2-d05cc07b2630.png">

**Comment by ahmehri** [comment]
No, I'm not planning on working on it. I'll comment here should I start working on it.

**Comment by adnasa** [comment]
btw, what was the "alternative" that you found?
it's not clearly stated in the PR you linked, but my intuition is that it ought to be `AccessibleButton`

**Comment by ahmehri** [comment]
All the other buttons are alternatives. The one mentioned in the linked PR is `<FlatButton />`.

> Adds as prop to FlatButton.

And I found out that all other buttons have also the `as` prop.

**Comment by mmaltsev-ct** [comment]
The agreement is to add the story for this component back to the storybook and make sure the deprecation note is visible in the README.
