### ISSUE TITLE
Expose hasError prop form the LocalizedTextField

### ISSUE THREAD

**Issue by mohib0306** [commercetools/ui-kit#1959]
**Is your feature request related to a problem? Please describe.**
The `LocalizedTextInput` exposes `hasError` prop and it can be used to visually indicate that the input has error and should be checked. However the `LocalizedTextField` does not expose this prop. It would be nice to have access to this prop to visually indicate that there is an error in the `LocalizedTextField`.
**Describe the solution you'd like**
`LocalizedTextField` accepts `hasError` and passes down to the internal `LocalizedTextInput` component.

**Comment by tdeekens** [comment]
Thanks for reporting.

The component as an `errors` object and a `renderError` callback outlined [here]https://github.com/commercetools/ui-kit/blob/main/packages/components/fields/localized-text-field/src/localized-text-field.js#L47-L60). It does not have a `hasError` cause it has various inputs one per locale and one should show an error per input to inform the user. 

Lastly, the `hasError` is forwarded to each input [here](https://github.com/commercetools/ui-kit/blob/main/packages/components/fields/localized-text-field/src/localized-text-field.js#L229) depending on the `errors` passed.

Does this somewhat help?

**Comment by mmaltsev-ct** [comment]
Hey @mohib0306, does Tobi's answer help? Do you think this feature request is something you'd still need for your work?

**Comment by mohib0306** [comment]
Tobi's answer suffice and I think we can close this issue.
