### ISSUE TITLE
LoadingSpinner - add setTimeout of one second before rendering

### ISSUE THREAD

**Issue by ByronDWall** [commercetools/ui-kit#1984]
**Is your feature request related to a problem? Please describe.**
[DCY-121](https://jira.commercetools.com/browse/DCY-121) and [PAN-1029](https://jira.commercetools.com/browse/PANGOLIN-1029) suggest implementing a `setTimeout` interval of 1 second to loading indicators so that loading indicators do not flicker for a few milliseconds 

**Describe the solution you'd like**
The solution I am considering is to implement a `setTimeout` that is called on mount of the `LoadingSpinner` component, which would set a local state value (e.g. `isActive`) that controls whether or not the `LoadingSpinner` renders.  If the `LoadingSpinner` dismounts before the 1 second interval is over, the timeout will be cleared with the `clearTimeout` method.

Currently, the LoadingSpinner has no `isActive` (or similar) prop/state value that controls whether the component renders.  I propose that the `isActive` value should be controlled by the component internally, and set exclusively by the `setTimeout` method that would run on mount.

Additionally, I propose exposing a prop named `noDelay` (or similar) that would allow for the `LoadingSpinner` to mount without the 1 second delay if there are usecases where a one second rendering delay would not be optimal.

**Additional context**
The rationale for this change is described in further detail [here](https://www.smashingmagazine.com/2016/12/best-practices-for-animated-progress-indicators/)

Additionally, in investigating implementing this change, I ran into an [issue](https://github.com/facebook/jest/issues/11500) in `jest` version 27+ that complicates testing timers such as `setTimeout` effectively.  Any guidance on best practices for testing timers in the UI-Kit test suite would be appreciated.

**Comment by emmenko** [comment]
Hey, thanks for the proposal.

In terms of implementation yes, I agree that we should use `setTimeout`.

As for the behavior, this is a question and decision to be made by the UX team. Have you talked to them already?

**Comment by ByronDWall** [comment]
> As for the behavior, this is a question and decision to be made by the UX team. Have you talked to them already?

I've confirmed with Ariana that this behavior is the desired UX for loading indicators, is there anyone else on the UX team I should also confirm this with?

**Comment by emmenko** [comment]
No then it should be fine. Thanks

**Comment by tdeekens** [comment]
Just to chime in briefly. The idea is nice and we use it internally already with an internal component. Just to share in case it went under the radar. It's called `delayed-spinner`. In case we build this into ui-kit (which seems worthwhile) we can then drop that component. Thanks for picking this up! You're API sounds great!

**Comment by ByronDWall** [comment]
> Just to chime in briefly. The idea is nice and we use it internally already with an internal component. Just to share in case it went under the radar. It's called `delayed-spinner`.

Thanks for mentioning this! I will take a look at the internal component to see how it was implemented, and will be adding the timeout functionality to ui-kit `LoadingSpinner` in the near future.
