### ISSUE TITLE
Setup release script

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#2]
We can let travis do the publishing to npm every time we push a new `tag`.

https://docs.travis-ci.com/user/deployment/npm/

Additionally, we can also decide to do "canary" releases (e.g. for `master` branch).

**Comment by adnasa** [comment]
I'd like to pair with someone on this.

**Comment by emmenko** [comment]
Is the task clear on what needs to be done?

**Comment by emmenko** [comment]
We can pair together if no one jumps in

**Comment by dferber90** [comment]
It would be nice if whoever tackles could add a `PUBLISHING.md` or a section in `README.md` about how we publish!

**Comment by emmenko** [comment]
Yeah, I would put it in `CONTRUBUTING.md`.

---

The general idea for publishing is that we only do that whenever we **create a `git tag`**.

**Comment by dferber90** [comment]
The job of the release should also be to create the netlify deployment. We currently deploy to `uikit.commercetools.com` straight from `master`, but this is confusing as it leads to `uikit.commercetools.com` being a different version than what is available under the `latest` dist-channel on npm.

**Comment by emmenko** [comment]
You can't "disable" the `production` branch from being deployed.

<img width="717" alt="image" src="https://user-images.githubusercontent.com/1110551/45094357-57cbaf80-b11b-11e8-83ea-a7f06199d926.png">

What we can do (maybe, I will have to try that first) is to rename the `production` branch to a “random” one and deploy using the Netlify CLI

**Comment by emmenko** [comment]
> We could also create a `development` branch and set it as the main one in GitHub

FYI: 👆 suggestion from @dferber90

**Comment by adnasa** [comment]
have you guys considered [gitflow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) for this?

**Comment by adnasa** [comment]
I want to make clear that I won't have time for this in the coming weeks.
anyone is free to pick this up.

**Comment by emmenko** [comment]
I'll take this over then since I'm off for the next couple of weeks and I'd like to get this done by tomorrow
