### ISSUE TITLE
MultiLine attributes wrapping by letter instead of by word

### ISSUE THREAD

**Issue by michaelashe** [commercetools/ui-kit#2050]
A UI/UX improvement opportunity for MC

Product descriptions and any custom product attributes with `inputHint: "MultiLine"` are wrapping at the individual character level rather than at the word level. It isn't saving this way, just rendering on the screen this way. This is coming from `word-break: break-all` in the CSS.

{{SUPPORT-14505}}

**Comment by mmaltsev-ct** [comment]
@michaelashe Thanks for reporting. We'll take a look at this and see what we can do.
