### ISSUE TITLE
@commercetools-uikit/rich-text-field  and @commercetools-uikit/localized-rich-text-input cannot update a component while rendering a different component

### ISSUE THREAD

**Issue by zombieleet** [commercetools/ui-kit#2075]
**Describe the bug**
Using `@commercetools-uikit/rich-text-field` and `'@commercetools-uikit/localized-rich-text-input'` produces the below error 

```
Warning: Cannot update a component (`UncontrolledCollapsibleMotion`)
while rendering a different component (`EmotionClassNames`). To locate the bad setState() call inside `EmotionClassNames`, 

Warning: Cannot update a component (`LocalizedRichTextInput`) while rendering a different component (`Editor`). To locate the bad setState() call inside `Editor`
```

**To Reproduce**

1. Go to https://replit.com/@zombieleet/SuperficialHoneydewRatio#src/App.tsx
2. Click on 'Run'
3. Click on the icon that indicates opening to a new tab
4. Go the new tab
5. Open the developer console (to see when the error will happen)
6. Click on the rich text field
7.  See the error
**Expected behavior**
The error should not be happening, the inputed message should be rendered on the console as well as the rich text field

**Comment by zombieleet** [comment]
@emmenko , Yes, I have rendered each of them individually, but the error is still showing. I will double check if I missed a required prop and get back to you. Thanks

**Comment by emmenko** [comment]
Closing, feel free to reopen if you still have issues.
