### ISSUE TITLE
Add `<ViewSwitcher>` component

### ISSUE THREAD

**Issue by MicheleRezk** [commercetools/ui-kit#2078]
**Is your feature request related to a problem? Please describe.**
Within our Operations App, we used a "core/shared component" to display a quick filter for our imported data. 
To now Improve MC consistency and usability, we should build a component out of the shared component we used.

**Describe the solution you'd like**
Introduce ViewSwitchers Component in UI Kit, which allow users to toggle between two or more different views of the same, similar or related content items within the same space on screen.

**When to use:**
ViewSwitchers are frequently used to let users toggle between different formattings, like with a grid view and a table view.
They are also often used to narrow content groups.
For example, use a content switcher if you have a list, such as “Import-results” and you want to divide it into views such as “All”, “Failed”, and “Success”.
![1](https://user-images.githubusercontent.com/30607195/151365212-b63ec82b-07db-40eb-86f4-dc4d7e869a93.png)

**Comment by Shecki** [comment]
https://wiki.commercetools.com/display/shield/ViewSwitcher%3A+component+checklist

**Comment by mmaltsev-ct** [comment]
Hey @MicheleRezk, could you clarify whether there was already any work done for this component in the ui-kit?

**Comment by MicheleRezk** [comment]
Hey @mmaltsev-ct , I still didn't start working on this component yet
