### ISSUE TITLE
Tag component don't use the right color for the text when disabled

### ISSUE THREAD

**Issue by CarlosCortizasCT** [commercetools/ui-kit#2090]
**Describe the bug**
When using the [Tag component](https://uikit.commercetools.com/?path=/story/components-tags--tag) and providing the **isDisabled** prop, visualized text should have a lighter color but it is using the same color as the non-disabled state.

**To Reproduce**

1. Go to the [component storybook page](https://uikit.commercetools.com/?path=/story/components-tags--tag)
2. Select the "knobs" tab
3. Check the isDisabled checkbox
4. You will see no change in the component but the text color should be lighter

**Expected behavior**
Text color of the component should be lighter when disabled.
We should be using the **secondary** _tone_ for the text in that context.

**Screenshots**
Current visualization when disabled:
![tag_ko](https://user-images.githubusercontent.com/97907068/152957163-6a1c1379-5090-496a-8869-554dda553fd6.png)

Expected visualization when disabled:
![tag_ok](https://user-images.githubusercontent.com/97907068/152957225-00782df1-d4e4-444e-895f-569235a7d289.png)

**Comment by FilPob** [comment]
Look good from my side 👍
