### ISSUE TITLE
Minor, dependencies:  loading-spinner or text do not provide react-intl

### ISSUE THREAD

**Issue by nkuehn** [commercetools/ui-kit#2101]
**Describe the bug**
Getting a warning in yarn 3 with pnp:
`@commercetools-uikit/loading-spinner@npm:12.2.9 [2ef48] doesn't provide react-intl (p61d0f), requested by @commercetools-uikit/text`

**To Reproduce**

1. Have a `package.json` indirectly or directly using the above components
2. `yarn install`

**Expected behavior**
No warning. 

**Additional context**
Not a priority, just tuning

**Comment by CarlosCortizasCT** [comment]
Hello @nkuehn,

Thanks for letting us know about this dependencies issue when using _yarn_ and _pnp_.

We will look into this specific case and also review other potential similar ones within the ui-kit repository.

We'll let you know once we have this addressed.
