### ISSUE TITLE
`touched` is expected to be an array of boolean when isMulti is true

### ISSUE THREAD

**Issue by bradd123** [commercetools/ui-kit#2162]
**Describe the bug**
When we are using `<SearchSelectField/>` and `<AsyncSelectFiled />` and isMulti is true, the below error is throwing when touched is undefined.

`Uncaught Error: Warning: SearchSelectField: touched is expected to be an array of boolean when isMulti is true`

**Comment by CarlosCortizasCT** [comment]
Hi @bradd123 

Thanks for letting us know about this unexpected behaviour.

We're going to look at it and let you know when we have some news about it.

**Comment by CarlosCortizasCT** [comment]
Hi @bradd123,

We found and fixed the problem with the warnings you've mentioned.

I keep the issue open until a new version of `ui-kit` is published with the fix.

**Comment by CarlosCortizasCT** [comment]
This change has been included in the published version `14.0.6`.
