### ISSUE TITLE
README storybook integration broken

### ISSUE THREAD

**Issue by dferber90** [commercetools/ui-kit#217]
![bildschirmfoto 2018-11-08 um 10 50 03](https://user-images.githubusercontent.com/1765075/48192423-0b356800-e348-11e8-9963-7f04da872482.png)
When viewing the deployed UI-Kit the README is only visible after a page refresh.

Reproduction:
1. open https://uikit.commercetools.com
2. switch to README tab

Expectation:
Readme is visible

Observed Behaviour:
"README.md was not added" is shown.

A page refresh at that point solves the problem.

This is likely to be a bug in Storybook itself.

**Comment by emmenko** [comment]
Related issue (still not fixed): https://github.com/tuchk4/storybook-readme/issues/102

**Comment by dferber90** [comment]
This is fixed in [v4.0.4 of `storybook-readme`](https://github.com/tuchk4/storybook-readme/issues/105#issuecomment-453225670), which came in with #426 🎉
