### ISSUE TITLE
Implementing Strikethrough Text

### ISSUE THREAD

**Issue by mmaltsev-ct** [commercetools/ui-kit#2217]
**Summary**
The strikethrough text (see example below) is used now in multiple parts of the Merchant Center. At the moment, teams use custom styling to achieve this state:

```HTML
<s className={styles.removed}>{value}</s>
```

Hence, it makes sense to consider implementing this as a part of the ui-kit.

Example use-case:
<img width="439" alt="image" src="https://user-images.githubusercontent.com/89984934/174750240-c5c8a834-0e16-4875-902f-5ccd1e7c4285.png">

**Comment by chloe0592** [comment]
@FilPob I thought about creating a `<Text.Striketrough>` component that has the same props as `<Text.Body>` (since that's what is being used now) except I would add `text-decoration: line-through` in styles. Do you have some other idea/comment/suggestion? Thank you!

![Screenshot 2022-10-11 at 12 54 00](https://user-images.githubusercontent.com/52276952/195072032-dde50a43-212f-4f9a-91d6-a9e8fab78e69.png)

**Comment by tdeekens** [comment]
> @FilPob I thought about creating a <Text.Striketrough> component that has the same props as <Text.Body> (since that's what is being used now) except I would add text-decoration: line-through in styles. Do you have some other idea/comment/suggestion? Thank you!

Great to see you working on this! That covering the use cases would depend a bit on what text styles would require to be strike-able, right? If we'd want headline and subheadlines to also be struck we might come along better with a prop on each component maybe?

**Comment by chloe0592** [comment]
That's a great point! Thank you!
So we could pass then it to each component like we do it with `Bold` and `Italic`, that's the idea, right?

> Great to see you working on this! That covering the use cases would depend a bit on what text styles would require to be strike-able, right? If we'd want headline and subheadlines to also be struck we might come along better with a prop on each component maybe?

**Comment by chloe0592** [comment]
This is then how it would work -->

![Screenshot 2022-10-11 at 13 13 13](https://user-images.githubusercontent.com/52276952/195075867-d07a3519-8f14-4954-af0a-3f0e5dea93e2.png)

 > Great to see you working on this! That covering the use cases would depend a bit on what text styles would require to be strike-able, right? If we'd want headline and subheadlines to also be struck we might come along better with a prop on each component maybe?

**Comment by tdeekens** [comment]
> This is then how it would work -->

Yeah, if any text should be strike-able certainly. Might also be an easier to understand API even if we don't expose it e.g. on headlines (for Maxium and Filip to decide).

**Comment by mmaltsev-ct** [comment]
> This is then how it would work -->
> 
> ![Screenshot 2022-10-11 at 13 13 13](https://user-images.githubusercontent.com/52276952/195075867-d07a3519-8f14-4954-af0a-3f0e5dea93e2.png)

Thank you Klaudija, it looks good to me 👍
Filip is quite busy now, but you can share this idea in Slack and ask for his point of view, should be a no-brainer, I think.
