### ISSUE TITLE
Unpredictable behavior DateInput when input by keyboard

### ISSUE THREAD

**Issue by planetcrypton** [commercetools/ui-kit#2261]
**Describe the bug**
When entering dates by keyboard (in stead of clicking the calendar UI), I expect to be able to enter any valid formatted date (and have that selected on the calendar UI) and hitting enter will change the date accordingly.
The example at https://uikit.commercetools.com/?path=/story/components-inputs--dateinput works perfectly, but my version of the component (v15.2.1) doesn't.

**To Reproduce & Expected behavior & Screenshots****
Compare the example in the documentation:

https://user-images.githubusercontent.com/1587059/186252866-d0ff9f59-bfe8-482e-b567-f836ae879b35.mov

with my example:

https://user-images.githubusercontent.com/1587059/186253000-b40bba15-fdff-4ce0-9bae-3c51c2184c43.mov

As you can see it only works as expected for months earlier than October 🤔; For month 10+11+12 the date never gets selected in the UI and thus hitting enter won't change the date. Whereas months < 10 work fine

**Additional context**
The app does nothing but displaying this `DateTest` component on this particular route. Code for that is in the screencast video

**Comment by ddouglasz** [comment]
Hello @planetcrypton ,
Thank you for reporting this. We are currently investigating the cause.
