### ISSUE TITLE
Adjust info button in the data table component

### ISSUE THREAD

**Issue by FilPob** [commercetools/ui-kit#2283]
**Is your feature request related to a problem? Please describe.**
The optional info button which can be set in the table header cell is currently 24px big and is placed left to the label. This causes a bad looking alignment with the rest of the table cells and due to the size, the padding of the header ell seems to be ignored

**Describe the solution you'd like**
- Set the size of the info button to **16px**
- Place the info button on the **right side** of the label
- The margin between the label and the info button should be **8px.**
<img width="568" alt="image" src="https://user-images.githubusercontent.com/94548534/189930713-c140f859-cceb-4df3-a7ce-9741bdc2316d.png">

**Comment by Pathholder1806** [comment]
Hey @FilPob !
I would like to contribute to this issue!
Can you please point the source file of this component as I am not able to find it.

**Comment by ddouglasz** [comment]
Hello @Pathholder1806, 
Thanks for volunteering to give this a shot. 
Actually, this is not an issue. The icon is just “passed” to the table and you can simply configure the icon to be rendered with a smaller size ([https://github.com/commercetools/ui-kit/blob/1dac882e3acd640404b42ce1e9d528e7296ac99f/packages/components/data-table/src/data-table.story.js#L1[…]90](https://github.com/commercetools/ui-kit/blob/1dac882e3acd640404b42ce1e9d528e7296ac99f/packages/components/data-table/src/data-table.story.js#L181-L190))
