### ISSUE TITLE
I want some examples for <ViewSwitcher>

### ISSUE THREAD

**Issue by satyam21041997** [commercetools/ui-kit#2352]
I have to use <ViewSwitcher> in my project and I have to load two templates for different tabs of <ViewSwitcher>.
Please provide some examples how to do that.

**Comment by kark** [comment]
Hi @satyam21041997,

Thank you for reaching out. In our storybook we provide 2 example stories with this component:
- [`<ViewSwitcher>` with icons](https://uikit.commercetools.com/?path=/story/components-viewswitcher--viewswitcher-with-icons)
- [`<ViewSwitcher>` without icons](https://uikit.commercetools.com/?path=/story/components-viewswitcher--viewswitcher-without-icons)

Examples of usage in controlled mode and uncontrolled mode can be also found in [README](https://github.com/commercetools/ui-kit/tree/main/packages/components/view-switcher).
You can also find some [recommendations](https://github.com/commercetools/ui-kit/tree/main/packages/components/view-switcher#when-to-use) when and how to use this component.

Please mind that we also provide components with navigational controls and route-driven content using Tabs:
- [`<TabularModalPage>`](https://docs.commercetools.com/custom-applications/api-reference/commercetools-frontend-application-components#tabularmodalpage)
- [`<TabularMainPage>`](https://docs.commercetools.com/custom-applications/api-reference/commercetools-frontend-application-components#tabularmainpage)
- [`<TabularDetailPage>`](https://docs.commercetools.com/custom-applications/api-reference/commercetools-frontend-application-components#tabulardetailpage)

Hope that solves your issue. If not, perhaps you can share some more information about your use case.

**Comment by satyam21041997** [comment]
Hi @kark ,
Thanks for your response. Now I am using `<TabularMainPage>`.
But I am still facing some problem:-
1.  How to select the one tab as default when the `<TabularMainPage>` will load.
2. How to give full height to the body of each Tab.
![image](https://user-images.githubusercontent.com/94686066/205482122-8082defa-7522-4fb1-985c-c585b673511b.png)

**Comment by satyam21041997** [comment]
Hi @kark ,
Thanks for your response
