### ISSUE TITLE
Increase `Tooltip` component `z-index` value

### ISSUE THREAD

**Issue by CarlosCortizasCT** [commercetools/ui-kit#2378]
**Is your feature request related to a problem? Please describe.**
The problem we might find is for a `Tooltip` component not being rendered on top of other elements in the page.

Currently this component has a `z-index` CSS property with a value of *1* which is a lower value so, if any other component nearby the location where the tooltip is supposed to be rendered has a greater `z-index`, the tooltip will be displayed behind it.

**Describe the solution you'd like**
Since tooltips use to contain very important context information, I think they should always be on top of everything else.
I would suggest to increase the `z-index` to a much higher value (for instance, *1000*). It's not 100% safe, but it will highly improve the chances of tooltip to not be rendered behind another elements in the page.

**Describe alternatives you've considered**
None.

**Additional context**
I've based this request on [this documentation](https://atlassian.design/foundations/elevation#z-index) from Atlassian design system where they have a `z-index` scale having the tooltips with the highest value.

**Comment by emmenko** [comment]
> I would suggest to increase the z-index to a much higher value (for instance, 1000)

Let's go for it!
