### ISSUE TITLE
application-component documentation lists incorrect code example

### ISSUE THREAD

**Issue by phofmann** [commercetools/ui-kit#2400]
Have a look here: https://docs.commercetools.com/custom-applications/api-reference/commercetools-frontend-application-components#infomodalpage
The example creates a pageModalState which is never used but refers to a function handleClose that does not exist.

**Comment by kark** [comment]
Hi @phofmann,

Thank you for reporting!
Could you please open this issue in the https://github.com/commercetools/merchant-center-application-kit repo (as that is where the docs are located)?

Thanks

**Comment by phofmann** [comment]
https://github.com/commercetools/merchant-center-application-kit/issues/2950
