### ISSUE TITLE
`Tag` component does not support content-driven width

### ISSUE THREAD

**Issue by CarlosCortizasCT** [commercetools/ui-kit#2434]
**Describe the bug**
When using the Tag component I would expect using the `auto` value for it's `horizontalConstraint` to make its width fit the its contents but, when doing so, the component width is 100% of its container (the same as when using the `scale` value).

**To Reproduce**

1. Go to the `Tag` component [story](https://uikit.commercetools.com/?path=/story/components-tags--tag)
2. Select `auto` in the `horizontalConstraint` knob
3. See the width of the tag is 100%

**Expected behavior**
I would expect the `Tag` component to have its width based on its content when using the `auto` value for its `horizontalConstraint` prop.

**Screenshots**
![image](https://user-images.githubusercontent.com/97907068/221517527-eac7cad1-85fa-4e8c-93b9-3a0f6c63f4b2.png)

**Comment by chloe0592** [comment]
@CarlosCortizasCT I'm not sure I follow what you wanted to do here. I tried looking into some other components like `Date field` or `Collapsable panel` to see what's the behaviour for `horizontalConstraint` there, but it seems to me it's the same as for `Tag`. 
Do you think these values for auto are incorrect? Or maybe I'm missing something else?

**Comment by CarlosCortizasCT** [comment]
Hi @chloe0592 

I was trying to find some information about how the `auto` value should work but I haven't found anything in the repo.

In my point of view, `auto` should work as disabling the horizontal constraint so the width of the wrapped should be guided by its contents.
If we check the [component story](http://localhost:9002/?path=/story/components-constraints--horizontal), we can see that `auto` and `scale` are rendering the same result, which is something I would not expect.
![image](https://user-images.githubusercontent.com/97907068/221824998-283a8923-08b3-4fb7-933a-2f4771f4f884.png)

I found this issue when trying to implement a view where tags should behave like this (content driven width):
![image](https://user-images.githubusercontent.com/97907068/221823646-a1b0b0fe-470a-4417-a8e8-b8d22f23c22f.png)

Perhaps @FilPob can provide more info about the `auto` value in the horizontal constraint component

**Comment by chloe0592** [comment]
What was decided: 

> Regarding the topic we discussed today around the auto value for the Constraint.Horizontal [component](https://uikit.commercetools.com/?path=/story/components-constraints--horizontal), I only found 4 usages in the MC frontend monorepo:
> application-account
> [team-member-invite-or-search-form](https://github.com/commercetools/merchant-center-frontend/blob/main/packages-application/application-account/src/components/team-member-invite-or-search-form/team-member-invite-or-search-form.jsx#L122) (in a select component)
> application-discounts
> [basic-predicate-view](https://github.com/commercetools/merchant-center-frontend/blob/main/packages-application/application-discounts/src/components/predicate-configurator/basic-rule-builder/basic-predicate-view.jsx#L159) (in a select component)
> [basic-rule-item-view](https://github.com/commercetools/merchant-center-frontend/blob/main/packages-application/application-discounts/src/components/predicate-configurator/basic-rule-builder/basic-rule-item-view.jsx#L145) (in a select component)
> application-products
> [internal-store-product-search](https://github.com/commercetools/merchant-center-frontend/blob/main/packages-application/application-products/src/components/product-search-form/internal-store-product-search.jsx#L64) (in a constraint.horizontal component)
> Attached is a screenshot of the first one.
> I think we could update those to use the scale value instead, since currently they behave the same, and (later) change the auto value behaviour in ui-kit.

**Comment by chloe0592** [comment]
This issue is being close right now since we don't have a use case of "auto" `HorizontalConstraint` for now and for the multiple tags inlined case we opened a new issue where we'll introduce a `TagList` component wrapper - [issue](https://github.com/commercetools/ui-kit/issues/2445).
