### ISSUE TITLE
Label component props table formatting 

### ISSUE THREAD

**Issue by jocelyn-dunkley** [commercetools/ui-kit#2472]
**Describe the bug**
There is some kind of markdown issue with the props table here so it's just showing up as a block of text

**To Reproduce**

1. Go to ['Form: Label'](https://uikit.commercetools.com/?path=/story/components-label--label)
2. Scroll down to 'Props'
3. See error

**Expected behavior**
The props table should look like a table like the other UI kit components. 

**Screenshots**
![Screenshot 2023-04-03 at 11 26 03](https://user-images.githubusercontent.com/115018694/229469061-87d4ab16-e6e8-4f19-8c42-6200a9a36702.png)

**Comment by kark** [comment]
@jocelyn-dunkley Thank you for reporting.
