### ISSUE TITLE
SelectableSearchInput menuPortalZIndex not being applied properly

### ISSUE THREAD

**Issue by jocelyn-dunkley** [commercetools/ui-kit#2477]
**Describe the issue**
When I am using the SelectableSearchInput the menuPortalZIndex seems to not be working and the dropdown is hiding behind items that are below it, as seen in the screenshot below. I have made the z-index 3 as well as the max option but neither works. For this particular case, the z-index of the "Actions" dropdown is only 2. 
![Screenshot 2023-04-03 at 10 40 16](https://user-images.githubusercontent.com/115018694/229459813-bc57756c-8509-4705-be33-aa140b8ca52c.png)

```
<SelectableSearchInput
            value={initialValueObject}
            placeholder={getBasicInputPlaceholder()}
            onChange={handleChange}
            options={getSearchOptions()}
            onSubmit={handleBasicSearchSubmit}
            onReset={props.clearSearchTerm}
            horizontalConstraint={16}
            menuHorizontalConstraint={3}
            menuPortalZIndex={10000000}
            isDisabled={props.isDisabled}
          />
```

**To Reproduce**

1. Go to 'Products list'
2. Click on 'All fields' dropdown
3. See error

**Expected behavior**
The dropdown will go over the Actions dropdown 

**Screenshots**

**Additional context**

Maybe this will give you a hint but my previous solution to solve this was to wrap a div around SelectableSearchInput that had z-index: 3.

**Comment by emmenko** [comment]
@kark I transferred the issue to the ui-kit repo.

**Comment by kark** [comment]
Hey @jocelyn-dunkley,

If you wish to use `menuPortalZIndex` prop you need to also set `menuPortalTarget`, for instance `menuPortalTarget={document.body}`. Could you please check if that solves the issue for you?
We will improve the docs in that regard.

Thanks

**Comment by jocelyn-dunkley** [comment]
Thank you @kark that worked for me! Yes please add it into the doc - it was not clear to use that in conjunction.
