### ISSUE TITLE
Introduce preset components

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#249]
This is an idea and proposal to simplify the usage of several things.

### The problem

Building a view using UI components is great, it makes it easy and fun. However there is one little issue that is kind of annoying and that you end up doing all over again: **duplicated messages**.

For example, when you build a form you usually need a `Cancel` and `Save` button. So you usually end up creating messages for those buttons because the UI components require you to pass a label.
This happens for other things that are spread all over the different views.
And of course you end up having **A LOT** of duplicated messages to be translated, when 99% of the cases might not be necessary.

<img width="668" alt="image" src="https://user-images.githubusercontent.com/1110551/48941592-6f495600-ef1c-11e8-82c5-dd4eec18a52c.png">

### The proposal

It would nice to have some sort of "preset" components that are translated and everything within the ui-kit, so that as a consumer we don't need to care about all those messages again.

For example:
- `<CancelButton>`
- `<SaveButton>`

...and whatever other components might be useful.

Thoughts?

**Comment by dferber90** [comment]
Yep, I wanted to build them as well. I also dislike having to redo the translations every time.

Seems like this is more on the ui-kit section rather than the design-system section. So far our components have been more on the the design-system side. We can either add a separate section for these types of components, or we could experiment with exporting the translations themselves for now (not sure how that would work).

Sidenote: I found the name "presets" quite confusing.

**Comment by emmenko** [comment]
> We can either add a separate section for these types of components

Yes, that's what I meant with the "preset" thingy. It's just a grouping for such components.

> Sidenote: I found the name "presets" quite confusing.

I know, I couldn't find a better name to describe this 😅

**Comment by emmenko** [comment]
Maybe instead of having such "pre-made" components in the ui-kit, we can put them into a new package in the app-kit so that the ui-kit just remains more on the design system side.

**Comment by emmenko** [comment]
Should we move this to the app-kit then?

**Comment by montezume** [comment]
I'm not sure I really like this idea. If the problem we are trying to solve is *duplicate messages in transifix`, why are we solving it with `preset react components`? Seems like something that should be solved by creating another group of `preset` translations.

**Comment by emmenko** [comment]
What do you propose?

**Comment by montezume** [comment]
Introduce these "Generic" messages either, into the core messages, or into a new message json file. Something like

en.json
```"Generic.Submit": "Submit"```

**Comment by emmenko** [comment]
If we put it in core it's only available for us internally. The idea was to make those components/messages available for general usage.

So if we put it in app-kit, we can only expose the translated messages if the "final" components are not in the app-kit itself. It would also be a bit weird I suppose to have those messages lying around without co-located components.

What would be the problem of having those "ready-to-use" components from the app-kit?

**Comment by montezume** [comment]
Then we could export include those language assets in the `assets` package in app kit?

I just don't like the idea of making preset "Cancel" and "Submit" buttons to solve the issue of duplicate strings in transifix.

**Comment by tdeekens** [comment]
Can't app-kit expose those?

```
export defineMessages({
   save: ...
})
```

and we do:

```
import { sharedMessages } from 'app-kit`

**Comment by emmenko** [comment]
Let's try with that first and see how it goes
