### ISSUE TITLE
SearchSelectInput UI seems different when redesign is toggled ON

### ISSUE THREAD

**Issue by jaikumar-tj** [commercetools/ui-kit#2503]
**Describe the bug**
The `SearchSelectInput` UI seems different when isMulti is passed as true. eg, The width of each tag is more than the actual content.

**To Reproduce**

1. Go to SearchSelectInput in storybook
2. Enable `isMulti` prop
3. Try to add select options from the SearchSelectInput

**Screenshots**
UI on left is how it is supposed to look. 
UI on right is a bug. (Confirmed by filip [here](https://commercetools.slack.com/archives/C04F6CF7NGK/p1682407662315729?thread_ts=1682407522.739989&cid=C04F6CF7NGK) ) 

<img width="1313" alt="Screenshot 2023-04-25 at 09 22 09" src="https://user-images.githubusercontent.com/83634106/234207488-ccd90849-73fb-4f53-a570-10331e1d9239.png">

**Comment by Rhotimee** [comment]
Hey @jaikumar-tj, thank you for reporting this bug. We will look into it.
