### ISSUE TITLE
`Delay` props for <Tooltip> component

### ISSUE THREAD

**Issue by jaikumar-tj** [commercetools/ui-kit#2550]
**Is your feature request related to a problem? Please describe.**
The <Tooltip> component has `closeAfter` prop but there is no `openAfter` prop. Currently it feels very disturbing when user moves their cursor and see a tooltip keeps popping up. It would be a better experience if the tooltip can display after few milli seconds

**Describe the solution you'd like**
Allow Tooltip to consume a extra prop for delay and display the tooltip after the delay (only if cursor stayed on top of it throught out the delay time). If user quickly hovers over and moves away, we don't display the tooltip to avoid disturbances.

**Describe alternatives you've considered**

**Additional context**
Right now, I'm creating custom `BodyComponent` with custom css and passing it to tooltip to achieve this. It would be better if the component itself provide such a option.

**Comment by chloe0592** [comment]
Hi @jaikumar-tj, thank you for opening this issue. 😊 

That's a really good point that we might need to first check with Filip.
Usually the wait time for tooltip is somewhere between 300-500 milliseconds if the cursor is at the same place.

**Comment by FilPob** [comment]
We had a short call with @jaikumar-tj  and @CarlosCortizasCT  and I also played around with different values for the delays [here](https://codesandbox.io/s/s93xsc?file=/demo.tsx) After that I would suggest to do the following: 

- Add an `openAfter` property with a default value of `300ms` 
- The default value for `closeAfter` should be set to `200ms`

- Adding a `Grow` animation just like in the example [here](https://codesandbox.io/s/s93xsc?file=/demo.tsx) would be also pretty cool.

**Comment by CarlosCortizasCT** [comment]
We also need to bear in mind the display animation should not happen if the user just moves the mouse over the tooltip but does not stay in it.

We most probably use a `setTimeout` when hovering the tooltip to delay the open transition but, if the mouse is not over the element by the time the timeout expires, we should now display the tooltip. We should cancel the timeout when mouse leaves the element.

**Comment by CarlosCortizasCT** [comment]
> * Adding a `Grow` animation just like in the example [here](https://codesandbox.io/s/s93xsc?file=/demo.tsx) would be also pretty cool.

@FilPob could you provide the duration you want for the animation?
Do you think users should have the change to change this duration?

**Comment by FilPob** [comment]
I think we can go with a fixed value first... I suggest 150ms.
