### ISSUE TITLE
Support for non-standard or x currencies for MoneyInput component. 

### ISSUE THREAD

**Issue by Ibidapo** [commercetools/ui-kit#2552]
**Describe the bug**
`MoneyInput and static methods` (e.g parseMoneyVaue) do not support Money with non-standard currency (x-currencies) created by the API . During creation of a Shipping Method through the API a customer assigned a non-standard currency or x-currency to a shipping rate price, which resulted in the excerpt below, but due to lack of support of this currencies with `fractionDigits` of -1 this resulted in an unexpected error of the MC.

Price:
```js
{
    type: "centPrecision",
    currencyCode: "XXX",
    centAmount: 570,
    fractionDigits: -1,
}
```

**To Reproduce**

1. Create a shipping method with a non-standard currency for the shipping rate price.
```json
{
    "name": "SUPPORT-21661-2",
    "description": "SUPPORT-21661",
    "taxCategory": {
        "typeId": "tax-category",
        "id": "47bf8c04-abd3-418f-8c44-8324d36f2db5"
    },
    "zoneRates": [
        {
            "zone": {
                "typeId": "zone",
                "id": "182c90b8-04ec-4532-b1b5-ae7a7d847eaf"
            },
            "shippingRates": [
                {
                    "price": {
                        "currencyCode": "XXX",
                        "centAmount": 570
                    }
                }
            ]
        }
    ],
    "isDefault": false
}
```

2. Access the shipping method page in Merchant Center
3. The page should crash

NB: I am currently working on a quick-fix for this issue. So issue will not be easily reproduced on the Shipping Methods page on staging once this ticket is merged. Another way to reproduce it will be to hardcode dummy values of the response from the API (or postman) into the codebase for testing.

**Expected behavior**
MoneyInput component should work for x-currencies as it does for standard/national currencies (e.g EUR, USD, GBP)

**Screenshots**
![Screenshot 2023-07-06 at 13 43 53](https://github.com/commercetools/ui-kit/assets/25581605/1f0003ba-d63a-4168-bef6-0e564bf2c5f8)

![Screenshot 2023-07-06 at 13 45 40](https://github.com/commercetools/ui-kit/assets/25581605/814392f4-b622-4e1c-8ecb-d167c67f7dac)

**Comment by CarlosCortizasCT** [comment]
Hi @Ibidapo 

Thanks for opening the issue regarding the money components in `ui-kit`.

I'd like to ask about the non-standard currency support to understand why it's needed.
The money components do actually expect for standard currencies to be used and, also, in the context of commecetools APIs, I can see in the docs we're supposed to only support [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) compliants ones.
