### ISSUE TITLE
Support for iconLeft on Search Select Input

### ISSUE THREAD

**Issue by ismaelocaramelo** [commercetools/ui-kit#2633]
**Is your feature request related to a problem? Please describe.**
The search select input does not have support for icon left as the rest of the selectors. To keep consistency with the rest of the selectors we have in place.

**Describe the solution you'd like**
Add the support for leftIcon property

<img width="452" alt="Screenshot 2023-10-23 at 13 01 37" src="https://github.com/commercetools/ui-kit/assets/21059277/9d9b2ee1-be82-4f7d-ab29-1eedb3b195fb">

References:
[Async select](https://uikit.commercetools.com/?path=/story/components-inputs-selectinputs--asyncselectinput)
[Select input](https://uikit.commercetools.com/?path=/story/components-inputs-selectinputs--selectinput)

**Comment by chloe0592** [comment]
Thank you @ismaelocaramelo for creating this issue!
I just wanted to check first with @FilPob if there could be some potential design concerns about this before we implement it in the code?

**Comment by FilPob** [comment]
Hey together, thanks for the contribution @ismaelocaramelo . I dont see any concerns for the addition from the design perspective :)
