### ISSUE TITLE
Different outline color for focused elements

### ISSUE THREAD

**Issue by jaikumar-tj** [commercetools/ui-kit#2652]
**Describe the bug**
The outlines of the focused elements' colors are not the same. Some component have green outline and others have browser default blue outline

**To Reproduce**

1. Go to any application in Merchant center
2. Keep pressing `Tab` key on your keyboard

**Expected behavior**
All focused element should have same outline to maintain uniformity

**Screenshots**
<img width="1240" alt="Screenshot 2023-11-27 at 18 02 32" src="https://github.com/commercetools/ui-kit/assets/83634106/4b9c65f5-9ea6-4266-8916-8164c09ebedc">

**Additional context**

**Comment by CarlosCortizasCT** [comment]
I would like to know @FilPob opinion on this one.

The way I see it, input elements have the branding visual need for a border when they are focused but I don't see the same for any other element which can get focus but that depends on what we want from the design side.

I understand the goal on visual consistency though, but at the same time I don't expect (for example) buttons to have an outline when they are active (and also focused) so perhaps the outline should only be visible when accessing the button with the keyboard.

Just sharing that this could be a big effort and probably not everything could be achieved from `ui-kit` as anything that can be focusable would require taking care.

**Comment by FilPob** [comment]
One positive side-effect of the rebranding: Our new primary purple color (that is used as border-color for inputs when focused) is much closer to the browser's (at least chrome) default blue outline that is used when focusing other elements. So at least it's not so disturbing as the previous blue-green combination. So honestly I would dare to say that even the status-quo with the new theme is "good enough" atm. (at least in Chrome, which is in fact the most used browser for MC)

**Comment by CarlosCortizasCT** [comment]
Thanks @FilPob 

Then I'll close this issue and we can come back in the future if needed.
