### ISSUE TITLE
LocalizedRichTextInput

### ISSUE THREAD

**Issue by ismaelocaramelo** [commercetools/ui-kit#2655]
**Describe the bug**
<LocalizedRichTextInput /> component isn't re-rendering when the props change. 

I tried to fixed by using the [key](https://github.com/commercetools/merchant-center-frontend/blob/91861518238f16c56c03b98d42b20d9ec6e870fa/packages-application/application-products/src/components/product-general-info-form/product-general-info-description/product-general-info-description.jsx#L59) but that makes the editor to re-render for every each input. 

**To Reproduce**
Using the branch 1628 in MC:

Project : context-demo-data-project-15

Store : acme

Tailored Product description : “A description”

1. Go to [product details](https://mc-15626.mc-preview.europe-west1.gcp.escemo.com/context-demo-data-project-15/products/94b17a25-2daf-4200-8132-8ed30dd740c8)
2. Select store **acme** 
4. The description should have acme tailored description data. Then type within the rich text input

**Expected behavior**
Be able to render the text when data change and allow the user to edit without causing multiples re-renders.

**Comment by kark** [comment]
Hey @ismaelocaramelo,

Thank you for reaching out. Let me repeat it here for future reference. After the initial render each RichTextInput within a LocalizedRichTextInput can only be reset by calling `resetValue` with the new value. You can find the implementation details [here](https://chat.openai.com/c/link_to_code_implementation) and [here](https://chat.openai.com/c/link_to_another_code_implementation). 

If you have further questions or need clarification, feel free to ask.

Thank you!

**Comment by kark** [comment]
Hi @ismaelocaramelo 👋,

Checking in to see if we can close this issue now?

**Comment by kark** [comment]
After confirming with @ismaelocaramelo, I'm closing this now as discussed
