### ISSUE TITLE
`hasWarning` prop is not supported in many`<*Input>` components

### ISSUE THREAD

**Issue by jaikumar-tj** [commercetools/ui-kit#2671]
**Is your feature request related to a problem? Please describe.**
Not all the Field components support the orange border when we want to display warning

**Describe the solution you'd like**
Some components like `SelectField` accepts the `hasWarning` props but the other field components like `TextField, MoneyField, etc` don't have the same prop
<img width="959" alt="Screenshot 2023-12-19 at 16 05 42" src="https://github.com/commercetools/ui-kit/assets/83634106/45331e97-6428-405c-963e-c9c601159368">

Pacman Team and Context Team have an upcoming feature that requires this feature in order to be implemented it in the MC. Otherwise, we have to get rid of the `Field` component and use the `Input` & `Text` components (i.e, replacing `<TextField>` from product detail page and use `<TextInput>` and `<Text.Body>` to achieve the same result)  which seems like going against the idea of using the existing components.

@AnjaBuerger , @mariabarrena and @FilPob already discussed and agreed on this.

Ideally all the `<*Field>` components should have `hasWarning` feature
<img width="217" alt="Screenshot 2023-12-19 at 16 06 12" src="https://github.com/commercetools/ui-kit/assets/83634106/3ce1f7d1-98c4-4cce-88b8-b2c1b6018a0b">

**Note: We(@commercetools/pacman-team-fe) were originally planning to contribute to the UI-kit repo in the next Q during our feature development stage to enable this feature. If we get any early support from @commercetools/shield-team-fe or @commercetools/context-team-fe  that would be much appreciated as well**

**Comment by jaikumar-tj** [comment]
Just for transparency, I'll write this here. 

It was decided that
- All `<*Input>` components should have `hasWarning` prop to display orange border
- All `<*Field>` component should have `warning` prop to display orange border + warning text below

@commercetools/pacman-team-fe will work on implementing this.

**Comment by chloe0592** [comment]
Hi @jaikumar-tj, I see your team has started working on this issue. Will your team be handling it all the way through? Thanks!

**Comment by obulaworld** [comment]
> Hi @jaikumar-tj, I see your team has started working on this issue. Will your team be handling it all the way through? Thanks!

Hi @chloe0592 Yes, the final PR for this is here: https://github.com/commercetools/ui-kit/pull/2698

**Comment by jaikumar-tj** [comment]
Hi @chloe0592, Please let us know if we need to do anything else other than what Chisom commented. We are not sure about all the procedures.

**Comment by jaikumar-tj** [comment]
@obulaworld can we close this ticket or is there anything pending?

**Comment by obulaworld** [comment]
We can close it now. Nothing is pending
