### ISSUE TITLE
SelectableSearchInput: Allow choice for data-* props to be routed to search input or option dropdown

### ISSUE THREAD

**Issue by jocelyn-dunkley** [commercetools/ui-kit#2673]
**Is your feature request related to a problem? Please describe.**
Recently we unmasked some components on the product list in FullStory in order to better track what users are doing. This does not touch real user data. It is recommended to use semantic selectors to select relevant component sections. However I ran into an issue with properly selecting the option dropdown value of SelectableSearchInput. All data-* props are automatically attached to the search input. While we can still get the necessary data with this method, it is visually confusing to attach a data prop with the option value to the search input. 

<img width="1383" alt="Screenshot 2023-12-22 at 11 31 33" src="https://github.com/commercetools/ui-kit/assets/115018694/d19fccbb-5911-43e3-8f20-788a6fe9ff5b">

**Describe the solution you'd like**
Allow an option for the data prop to be routed to the search input or the option dropdown

**Comment by ddouglasz** [comment]
Hey @jocelyn-dunkley 
Thank you for pointing this out and suggesting a solution. We are currently taking a look at it.

**Comment by ddouglasz** [comment]
Hello @jocelyn-dunkley 
Please I would like to confirm if these "data attributes" we want to make available are expected to be provided to each option individually or to all options?

**Comment by jocelyn-dunkley** [comment]
@ddouglasz I think it should just have 1 data attribute attached to the dropdown component itself. On the product list side I am able to get what option was selected since we have a useState that keeps track of the "search mode" used, ie. search by all props, search only by product name, etc. We use this within the onChange function that is passed to SelectableSearchInput. So if the data-attribute is attached to the dropdown component itself I will have the up-to-date option that is selected at any given time. 

Let me know if that makes sense.

**Comment by ddouglasz** [comment]
This makes sense. 
Thank you!
