### ISSUE TITLE
`LocalizedTextField` should allow passing `errorsByLanguage` as React nodes and not only as strings

### ISSUE THREAD

**Issue by YahiaElTai** [commercetools/ui-kit#2730]
**Describe the bug**
I'm currently using `LocalizedTextField` which renders multiple inputs for all the languages, I want to show error under each language and not a global error under the whole field, because of this I'm passing the prop `errorsByLanguage` to `LocalizedTextField` which in turn gets passed to `LocalizedTextInput` As far as I can see in the code [here](https://github.com/commercetools/ui-kit/blob/main/packages/components/fields/localized-text-field/src/localized-text-field.tsx#L296) which is used [here](https://github.com/commercetools/ui-kit/blob/main/packages/components/inputs/localized-text-input/src/localized-text-input.tsx#L347)

As you can see from the the code, the error per language is being rendered as it is meaning, not allowing translation or even rendered within `ErrorMessage` to show it in red color. because of this I think this input should change the prop requirements to allow passing nodes.

**Expected behavior**
Because the errors are rendered as is, I expect to be able to pass a node to allow me to pass my own custom component (without facing prop validation errors) which would allow me to add translations to my errors and also have control over the color options (red color mostly)

**Screenshots**
<img width="734" alt="image" src="https://github.com/commercetools/ui-kit/assets/30247059/194a5856-55e8-41af-8aa8-68683ca24ae1">

**Comment by CarlosCortizasCT** [comment]
Hello @YahiaElTai 

Yes, we currently have an issue with this field is some components.
What you can do as a short-term action is to just provide the message wrapped in an `ErrorMessage` component as done in the [component story](https://github.com/commercetools/ui-kit/blob/main/packages/components/fields/localized-text-field/src/localized-text-field.story.js#L114). You will have a typing error, but you can safely ignore it while we work in a proper solution.

The idea is actually to keep accepting only strings but make the component use the right styles for it.
However, we know about many usages where consumers are doing what I've just suggested so we will implement the fix in a way that will support that behaviour as well.

**Comment by YahiaElTai** [comment]
> Hello @YahiaElTai
> 
> Yes, we currently have an issue with this field is some components. What you can do as a short-term action is to just provide the message wrapped in an `ErrorMessage` component as done in the [component story](https://github.com/commercetools/ui-kit/blob/main/packages/components/fields/localized-text-field/src/localized-text-field.story.js#L114). You will have a typing error, but you can safely ignore it while we work in a proper solution.
> 
> The idea is actually to keep accepting only strings but make the component use the right styles for it. However, we know about many usages where consumers are doing what I've just suggested so we will implement the fix in a way that will support that behaviour as well.

Thanks a lot @CarlosCortizasCT  for the quick reply and yes currently that's what we are doing, I guess we will keep our usage the same for now until a proper solution is given. Thanks a lot and I will close this issue

**Comment by CarlosCortizasCT** [comment]
I'll keep this issue opened so we can keep track of the problem and use it as a reference to solve it.
