### ISSUE TITLE
Rich Text Input removing soft breaks and all empty paragraphs from the output markup

### ISSUE THREAD

**Issue by kark** [commercetools/ui-kit#2772]
**Is your feature request related to a problem? Please describe.**

Reported issue with the Rich Text Input
> Rich text editor in MC erases all empty lines before the data get saved. Is there a way to force an blank line using the UI. Other editors allow the usage of Shift+Enter to create a `<br />` or empty `<p />` which is convenient for MC users

**Describe the solution you'd like**
Rich text input including soft breaks in the output markup to enable users vertical separation of content

**Describe alternatives you've considered**
*-*

**Additional context**
- The current behaviour was introduced to enable Rich Text Input integration with Formik ([ref](https://github.com/commercetools/ui-kit/pull/2192))
- Evaluate possibility of using https://github.com/ianstormtaylor/slate-plugins/tree/master/packages/slate-soft-break

**Comment by jaikumar-tj** [comment]
@kark JFYI, there is an additional [sanitize function](https://github.com/commercetools/merchant-center-frontend/blob/eb0827f0cd8a4f48ba1cae19377c17da619c4e02/packages-application/application-products/src/product-details/conversions.js#L164) added in MC Product detail page (for rich text description) which removes all the `<p>` tags. Even if the UI-kit supports empty lines, Pacman and Context team will have to rework to tackle this in the FE.

**Comment by kark** [comment]
@jaikumar-tj Thanks for sharing 👍
