### ISSUE TITLE
SecondaryButton toggle styling seems to be broken

### ISSUE THREAD

**Issue by NickDevG** [commercetools/ui-kit#2775]
**Describe the bug**
When using [SecondaryButton](https://uikit.commercetools.com/?path=/story/components-buttons--secondarybutton) as toggle button (`isToggleButton = true`) and then clicking on it  (updating `isToggled` value), no visual effect is shown on the button

**To Reproduce**
1. Open story book [SecondaryButton](https://uikit.commercetools.com/?path=/story/components-buttons--secondarybutton)
2. Go to the knobs tab and select the checkbox for `isToggleButton`.
3. Check `isToggled`.
4. See no change on the button

**Expected behavior**
When selected the button as toggle should show the isToggled styling as the selected button in the [ViewSwitcher](https://uikit.commercetools.com/?path=/story/components-viewswitcher--viewswitcher-without-icons)

**Screenshots**

![Screenshot 2024-04-11 at 10 33 41](https://github.com/commercetools/ui-kit/assets/29254006/e245cae5-0880-437a-925e-d1a256b714d9)

![Screenshot 2024-04-11 at 10 34 07](https://github.com/commercetools/ui-kit/assets/29254006/ffe09d6e-aed9-4d3f-8570-c1a782e6efc3)

**Comment by CarlosCortizasCT** [comment]
Sorry for the late reply, @NickDevG 

We're working on a fix for the issue you found.

Thanks for reporting.

**Comment by NickDevG** [comment]
That is really good to know @CarlosCortizasCT , thanks for the update
