### ISSUE TITLE
dropdownmenu list menu content: menu content is not reachable if out of viewport

### ISSUE THREAD

**Issue by gabriele-ct** [commercetools/ui-kit#2786]
A quick video describing the issue:

https://github.com/commercetools/ui-kit/assets/106664971/a315b7aa-2194-4022-8392-16233c0f9e9a

**Expected behavior**
All the items should be accessible even if they initially appear out of the viewport

**Comment by CarlosCortizasCT** [comment]
Thanks for reporting @gabriele-ct 

Just for us to have more context, I can see two problems:
* The initial intention for this component is to block the page scroll when the dropdown is displayed to avoid needing a position recalculation of the dropdown while scrolling (easy to get into performance issues)
* We need to think what to do with the dropdown positioning: currently is always placed below the triggering element but, if the triggering element is down the viewport, we might want to consider positioning it above it.

Not super easy things to address.

**Comment by dinesh99639** [comment]
Can we have the dropdown position based on viewport position of dropdown input such as

If dropdown input is above the half of the viewport height:
- show dropdown below

else:
- Show dropdown above

In both the cases, if height of dropdown goes above or below the viewport, then display scrolling within the dropdown.

I'm willing to work on this issue if this is a feasible solution.

**Comment by FilPob** [comment]
@CarlosCortizasCT Not sure if it's related to this PR but I am pretty sure we will also need a max.height prop in this component in the future. E.g in the filter dropdown, when the list of options will get too long, the content will need to be scrollable. Let me know if I should create a short sync for us for this 
<img width="340" alt="image" src="https://github.com/commercetools/ui-kit/assets/94548534/3dfac794-6980-43ad-9bea-8a7562ac7cdd">
