### ISSUE TITLE
Adding iconLeft to SearchSelectInput with a long value selected shows incorrect layout of input

### ISSUE THREAD

**Issue by Sarah4VT** [commercetools/ui-kit#2805]
To recreate the layout issue, look at the SelectSearchInput component with a long value selected. Add an iconLeft value to add an icon to the left side of the input. The result is the icon is on a top row above the input value and icons on the right.

![Zight Recording 2024-04-30 at 04 35 40 PM](https://github.com/commercetools/ui-kit/assets/4260326/bcc66299-d6ac-4150-b11a-c78746ac994a)

_Originally posted by @Sarah4VT in https://github.com/commercetools/ui-kit/issues/2801#issuecomment-2087167748_

**Comment by ddouglasz** [comment]
Thank you for catching this . We will take care of it.
