### ISSUE TITLE
MoneyInput component throwing error for Belarusian ruble currency (BYN).

### ISSUE THREAD

**Issue by Ibidapo** [commercetools/ui-kit#2820]
**Describe the bug**
MoneyInput component does not support Belarusian ruble currency (BYN). A user (not a customer or partner yet) has reached out about an error when trying to select the currency `BYN` for a zone rate when creating a shipping method in the MC. While investigating the issues, I was also able to trace and reproduce this issue on `MoneyInput `component in the UI Kit library.

[SUPPORT-26458](https://commercetools.atlassian.net/browse/SUPPORT-26458)

**To Reproduce**

1. Go to MoneyInput component on UI Kit Library
2. Add `BYN` to list of currencies in the Knob Tab
3. Select `BYN` currency in MoneyInput component
4. See error in console log

**Screenshots**
<img width="1472" alt="Screenshot 2024-05-16 at 15 58 25" src="https://github.com/commercetools/ui-kit/assets/25581605/853559d3-1ff6-4ab5-a75e-353d17147a66">

<img width="1904" alt="26458after" src="https://github.com/commercetools/ui-kit/assets/25581605/1083ae6b-8c37-45b9-b4e6-05fa9c4ce7b3">

**Comment by Rhotimee** [comment]
Thanks for reporting this @Ibidapo. We will take a look at the issue.

**Comment by Ibidapo** [comment]
My pleasure @Rhotimee, in case the Team doesn't have the bandwidth to resolve the issue at this time. I'm more than happy to give it a go.

**Comment by ddouglasz** [comment]
>... in case the Team doesn't have the bandwidth to resolve the issue at this time. I'm more than happy to give it a go.

Hello @Ibidapo , this has been fixed and will be shipped with the next uikit release. Thank you
