### ISSUE TITLE
Add `maxLength` prop to `TextInput` and `TextField` and forward it to their input element

### ISSUE THREAD

**Issue by ragafus** [commercetools/ui-kit#2860]
**Is your feature request related to a problem? Please describe.**
As a developer, I'd like to be able to render a `<TextField />` which max value length allowed is 1.
I need to limit some form field values to a max. length.

**Describe the solution you'd like**
I'd like to have the native behavior of the browser https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength
For that I'd like to add a new prop `maxLength` to `TextInput` and `TextField` which should be forwarded to their input element.

**Describe alternatives you've considered**
None, because we have a native/standard behavior.

**Additional context**
This field would render with `<TextField maxLength={1} {...otherProps} />`
![Screenshot 2024-07-23 at 13 06 26](https://github.com/user-attachments/assets/53907c0b-0970-4559-a6d5-30bb17ca95f4)

**Comment by ragafus** [comment]
I created a PR that could also help as an starting point https://github.com/commercetools/ui-kit/pull/2854/files
Feel free to close it if it becomes useless.

**Comment by ddouglasz** [comment]
Thank you @ragafus , we will go give it a look.
