### ISSUE TITLE
<Text.Detail> Missing id forwarding results in a difficulty for testing field components

### ISSUE THREAD

**Issue by ragafus** [commercetools/ui-kit#2867]
**Describe the bug**
Field components forward an internal id called `sequentialErrorsId` to the `FieldErrors` component. `FieldErrors` component forwards this id to `ErrorMessage` component. `ErrorMessage` components forwards this id to `Text.Detail`. And `Text.Detail` components does NOT always forward this id to the underlying element.

This missing id results in difficulties when testing a form field: with testing library, it becomes difficult to identify which element contains the error message. So, test cases where error messages are checked need of boilerplate code.

**To Reproduce**

1. Go to any app that renders ui-kit field components
2. Make one form field be in an error state.
3. Inspect the DOM

**Expected behavior**
I expect the `sequentialErrorsId` to be forwarded to the underlying element to easily identify the error message when testing.
`expect(field).toHaveErrorMessage("whatever")`

**Screenshots**
![Screenshot 2024-07-25 at 14 08 56](https://github.com/user-attachments/assets/36b66a2a-6591-4fb8-8532-24ba9118ea61)
![Screenshot 2024-07-25 at 14 09 15](https://github.com/user-attachments/assets/26902894-979b-4ec0-8a82-0688692500b5)

**Comment by ragafus** [comment]
I've created an initial PR https://github.com/commercetools/ui-kit/pull/2866
Feel free to close it at any time if stale

**Comment by ddouglasz** [comment]
Thank you for reporting this. We will review the PR and update you.
