### ISSUE TITLE
Add tone prop to Text.Headline

### ISSUE THREAD

**Issue by jocelyn-dunkley** [commercetools/ui-kit#2886]
**Is your feature request related to a problem? Please describe.**
As part of the Identity Auth screen design we want to change the color of the headers and links to be --color-primary-30. This is available via the tone prop = "primary" value in Subheadline. It's also in Body and Detail. But there's no way to change the color of h1 or h2 right now via UI kit.

**Describe the solution you'd like**
Please add the same tone prop to Headline. 

**Describe alternatives you've considered**

**Additional context**

**Comment by ddouglasz** [comment]
Thanks for reporting. Will have a discussion with the designer if this was deliberate, otherwise, this will be worked on. Thanks!
