### ISSUE TITLE
Refactoring of `Buttons`

### ISSUE THREAD

**Issue by lufego** [commercetools/ui-kit#29]
Our current buttons implementation look enough (they are in UI Kit, they are implemented and work). But, if you take a closer look, they actually hold wrong concepts and different props.

## 1. Concepts

> We misuse some concepts about buttons, like:

- A `PrimaryButton` was supposed to be a primary ACTION button, the action we would suggest our users to take first, that is. But it was extended with a prop called `type`, and now it can be urgent.

- A `SecondaryButton` in the other hand, is supposed to be a secondary ACTION we would suggest our users to take. But we implemented a prop called theme, and it can be blue. (blue is actually used for information in the application)

Quick example from Apple design system:

<img src="https://user-images.githubusercontent.com/14938754/43202345-8b40b9e4-901b-11e8-8800-f2a3857c535b.png " width="400" />

- A `GhostButton` can be used to trigger tertiary actions. But we don't even use it. It could be simply removed (we actually use it once, but we can revisit it since its not necessary there)

- A `FlatButton` is what we use for tertiary actions. We currently have types for this, and actually our "LinkButton" has same styling as the "secondary" type.

And so on and so forth...

## 2. Props naming (theme, tone etc)

We can see in the mind map below, we use **inconsistent** names for props across our buttons. That makes the understanding of them quite complicated. What we want in the end is just to achieve some different style (exception for a link button or submit button, which we can have different component for).

----

To help illustrate all of this topics, I made the mind map below:

❌ **Current approach:**
![image](https://user-images.githubusercontent.com/14938754/43201746-a6322dca-9019-11e8-95e8-1b08ac9cd247.png)

✅ **Proposed approach:**
![image](https://user-images.githubusercontent.com/14938754/45100675-2ad2c900-b12a-11e8-8478-ee94a6b9cf8b.png)

----

Any thoughts? objections?

**Comment by emmenko** [comment]
Closing as we won't look into this any time soon.
