### ISSUE TITLE
[Docs] Inconsistent / missing props in the component READMEs

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#319]
**Describe the bug**
I noticed why using the components that the READMEs are not up-to-date with the components. For example, some props are not documented, are wrong or inconsistent.

**Expected behavior**
The READMEs should always reflect and document the components APIs.

**Comment by dferber90** [comment]
Thanks for the report :) As it is right now, this issue doesn't seem actionable unless there is a list of actual inconsistencies we need to fix. Could you share that?

Another thing we could do is to have somebody go through all ui-kit components and compare the docs to the actual props. However I don't see too much value in that. It seems fine to fix these doc issues as we notice them. It's not like things are super out of hand at the moment. #293 fixes some of the inconsistencies in docs as well.
