### ISSUE TITLE
Typescript support + generated docs

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#320]
I've been thinking about this for a while and I think the ui-kit it would be a perfect place to start using types.
I believe the most suitable option for the ui-kit is to use Typescript, as it's a public library and the ts adoption/support is much better, which makes it easier to consume.

Besides the advantages of typing the components, we can also leverage the types to auto-generate certain things, like props (instead of manually maintaining this, which causes inconsistencies). For example: https://www.npmjs.com/package/react-docgen-typescript.
I opened another issue that points to that problem: #319 

Let's think about this as a long-term solution, we don't need to jump on this right away.

**Comment by emmenko** [comment]
Update: we have the tool now to generate the READMEs. Once we're done with that, we will start with the TypeScript setup.

**Comment by adnasa** [comment]
removed `[Idea]` since the TS migration has started 😉

**Comment by mmaltsev-ct** [comment]
Typescript migration is ongoing and the tool to generate READMEs is working well. Hence, closing the issue.
