### ISSUE TITLE
Allow Tag to be flexible in height

### ISSUE THREAD

**Issue by adnasa** [commercetools/ui-kit#323]
**Is your feature request related to a problem? Please describe.**

For the moment, there is a design token setting a fixed height on `<Tag>`

https://github.com/commercetools/ui-kit/blob/539ec7b20f55f819220cb87b50a939c5216f8217/src/components/tag/tag.mod.css#L6

Although fair and fine, it turned out that this constraint broke pieces of the UI I work with.

![image](https://user-images.githubusercontent.com/462507/49881043-adf07300-fe2d-11e8-852b-5918492be555.png)

Clearer example on storybook

![image](https://user-images.githubusercontent.com/462507/49881089-c52f6080-fe2d-11e8-88df-b5d8de52cbfb.png)

**Describe the solution you'd like**

I don't want to remove the constraint on the height entirely, instead this component could set a min-height and not just height.

**Additional context**

I've talked to Camilo and Maria about the functional requirement on this, and decided that it would be worth to have it allow height flexibility, even though that the cases where height flexibility is required are exceptional.

**Comment by montezume** [comment]
Should we be adding some padding so that when the Tag is multiple lines, it looks consistent with a regular tag? 

(with min-height and no other changes)
![screen shot 2018-12-12 at 5 21 12 pm](https://user-images.githubusercontent.com/2425013/49883149-5d2f4900-fe32-11e8-8d33-3c633775c8d4.png)

cc @coolmilo

**Comment by coolmilo** [comment]
@montezume yes, let's keep consistency.
