### ISSUE TITLE
Support submit-on-enter for buttons

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#340]
**Describe the bug**
When working on forms, it's normal to use buttons with `type="submit"` that will cause the form to be submitted on **Enter**. At the moment, our buttons do not support that.

**Expected behavior**
I can use a button that behaves like a "submit", so I can press **Enter** to submit the form.

**Comment by tdeekens** [comment]
Note, that `submit` is the default `type` on buttons. Moreover, the current behaviour of the login form (to my memory) breaks in Firefox when using a password manager.

**Comment by emmenko** [comment]
Yes. The problem is that our button is hardcoded with `type="button"`.

> Moreover, the current behaviour of the login form (to my memory) breaks in Firefox when using a password manager.

Ah interesting. Do you remember what exactly breaks?

**Comment by tdeekens** [comment]
> Yes. The problem is that our button is hardcoded with type="button".

...and we maybe want to keep defaulting to `button` to not have it a breaking change.

**Comment by emmenko** [comment]
Yes of course, we should probably make it opt-in

**Comment by tdeekens** [comment]
> This would not be a breaking change as we can make type optional and keep defaulting to "button".

Yes that's what I would prefer too.
