### ISSUE TITLE
Q: typography styles

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#382]
As I was [playing around with ui-kit being used with e.g. Gatsby/Next.js](https://github.com/commercetools/ui-kit/issues/353#issuecomment-449629247), I noticed that the `Text` components use kind of "global styles", even though the styles are defined in the css file.

https://github.com/commercetools/ui-kit/blob/d1acba93d97419f8a85db51471edf602087515fa/src/components/typography/text/text.mod.css#L15-L70

I'm wondering about a couple of things:
- should we really target html tags instead of using specific classes?
- if we do want to have it like this, we should maybe move those selectors to our e.g. `reset.mod.css`

Thoughts?

**Comment by montezume** [comment]
Yeah I think we should fix this, it doesn't make sense to apply these styles globally. Plus, with VRT it should be easy to test.

**Comment by tdeekens** [comment]
I think it should be a local and not global. Why did we make them global back then? I assume it's also non breaking as it's just encapsulated to the component.

**Comment by emmenko** [comment]
The only side effects that I can think of is that if we still use h1,h2,... elements directly, the styles will be wrong once we make them local.

**Comment by emmenko** [comment]
I just checked, we still use some of them directly.

**Comment by montezume** [comment]
then for now we can add it [here](https://github.com/commercetools/merchant-center-application-kit/blob/e9a0b809346b690e6efffb40d99a66d2c09f583e/packages/application-shell/src/components/application-shell/reset.mod.css)

**Comment by tdeekens** [comment]
Maybe add them there while refactoring the typo to use classes and not globals to be able to mark the global ones as deprecated?

**Comment by dferber90** [comment]
> Why did we make them global back then? 

We inherited that code. I don't think it was given much thought when it was introduced at first. It is very likely a leftover from days before css-modules even.

> should we really target html tags instead of using specific classes?

No we don't want that. We have #185 open, which addresses this as well. One goal of #185 is to avoid using global styles (see "Ideal solution" in that document). It's not written using the words "global styles", but avoiding them is basically what it aims for.

**Comment by emmenko** [comment]
Good, I think we all agree then. I guess we can remove the "global" selectors and release as a major again (since it's a breaking change).

**Comment by montezume** [comment]
FYI I'm working on this now
