### ISSUE TITLE
Add more visual regression tests (interaction based)

### ISSUE THREAD

**Issue by montezume** [commercetools/ui-kit#400]
Now that we can interact with components before snapshotting them, we should add snapshots for components that have visual states that cannot be controlled via props. When I was working on #387, I found that I had to manually test the `Select` inputs, to check the styling of them when they are open wasn't broken. We should add tests for open states of these inputs.

**Comment by dferber90** [comment]
We've added some more tests now 🎈 

Closing this after speaking to @montezume as the task doesn't have a clearly defined goal and it's unlikely we'll add tests for "everything" right away.

We'll add more VRTs to existing components before refactoring or when stuff breaks.
