### ISSUE TITLE
Add warning state to localized inputs e.g. <LocalizedTextInput>

### ISSUE THREAD

**Issue by tdeekens** [commercetools/ui-kit#41]
### Summary

All simple inputs support both error and warning states. In recent discussions with design we learned that we also need warning states on localised inputs. Just like their error messages.

### Description

Given an e.g. <LocalizedTextInput> is used I want to pass `warnings` just like `errors` which are rendered under the respective localisation in orange tone.

### Alterantives

Showing the warning above the input itself. This however does not work when e.g. wanting to recommend (not enforce through errors) that a single localisation is unique across a set of entities.

### Visuals

![image](https://user-images.githubusercontent.com/1877073/45417387-5a318a80-b682-11e8-85db-f06af789a1be.png)

**Comment by dferber90** [comment]
@tdeekens Thanks for bringing it up! I was curious whether we have a use-case for the warnings and left them out on purpose initially. Now that we have one, I'm totally fine with adding it.

One open question: When an error and a warning is passed, would you expect both to be displayed? Or should the component only show the error in that case? The border colour of the input would currently be red (from the error), as the `TextInput` gives precedence to the `hasError` prop.

@lufego Do you wanna pick this one up?

**Comment by tdeekens** [comment]
> Now that we have one, I'm totally fine with adding it.

It's rather a theoretical one. I also asked for more use cases and no others are known yet. 

I think it's decent here to keep track of this at least.

> When an error and a warning is passed, would you expect both to be displayed? 

Personally, I think errors should take precedence over warnings. Warnings can after all be skipped.

**Comment by lufego** [comment]
Question: is the user able to save the custom view even tho he has this warning?

**Comment by lufego** [comment]
Cool, so I'll work on that later today

**Comment by tdeekens** [comment]
No need yet. You can if you want to but it's not an urgent request.
