### ISSUE TITLE
[Idea] do no bundle svg icons, expose only generic icon component

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#436]
Given our recent discussions about icons and some of the problems / limitations we had with them, I've been thinking about a possible approach that we can take to scale better and to make our lives easier.

## Current problems
At the moment adding/managing icons is quite cumbersome: we need to get svg files from designers, make sure the file name is correct, do a new release.
Per se it's not that bad. However, this means that for each new icon we would need to do the same.
Our icons set is also quite small, and sometime we have opinionated icons that are usually used for specific places and that can't be reused.
Furthermore, the bundle size of the ui-kit will keep increasing as we add new icons (and tree-shaking is broken at the moment anyway #307)
Last but not least, consumers of ui-kit are tight to the icons set that we expose, giving not many choices, unless they reimplement the Icon component and use custom svgs.

## A brighter path forward
In some of our recent experiments/discussions (e.g. #425), some ideas came up about having a more generic implementation to allow any kind of SVG icons to be used. For example, the SVG is loaded asynchronously by the `<Icon>` component, or SVGs are passed as base64 strings.

I think we should think about moving into something like that, which brings several benefits:
- smaller bundle size (svgs are not bundled anymore)
- tree-shaking works again
- opinionated icons/svgs do not need to "leak" into the ui-kit anymore
- (custom) applications can use whatever SVGs they want
- dynamic rendering of icons (e.g. `switch`)

What do you think? Should we do some spikes to look into that?

**Comment by tdeekens** [comment]
Nice ideas and thanks for pushing this.

1. Generally a restricted icon set is likely what designers and a Design System wants
    - A list of all possible icons to communicate them via names
    - They're restricted to what we expose but can still use any icon (they just need to set that up)
2. The bundle will be smaller but of the same size given consumers use the icons
    - Assuming that nobody uses all icons, yes the wasted bundle size decreases

I find for instance "opinionated icons do not leak into UIKit anymore" a bit too vague. Which icons are too opinionated and should not be in there. Have designers said the same?

All in all I am not saying we should not do anything but go maybe a decent middle ground. 

1. UIKit has a generic `Icon` component which can take a `url` or `base64` prop to render an icon
2. UIKit can still expose (a maybe boiled down to the minimum) set of pre-existing icons using that component `const ArrowUp = <Icon base64={...} />`
3. UIKit can use the `withSize` and `withThemeProp` internally and expose it through the `Icon` component accepting a `size` and `theme`

**Comment by emmenko** [comment]
> I find for instance "opinionated icons do not leak into UIKit anymore" a bit too vague. Which icons are too opinionated and should not be in there. Have designers said the same?

To give a couple of examples (scrolling through the list as I type): `CartIcon`, `LogoutIcon`, `TagMultiIcon`, etc.
I find those to be very specific to certain cases and difficult to use in other context, as opposed to a e.g. `AddIcon`.
Those "specific" icons can simply live in the application code directly.

> The bundle will be smaller but of the same size given consumers use the icons

That depends I guess if we still ship the icons together with the ui-kit or with a different package. But in general I think it will be much smaller yes.

**Comment by montezume** [comment]
<img width="613" alt="screen shot 2019-01-15 at 10 02 00 pm" src="https://user-images.githubusercontent.com/2425013/51209748-42f4f900-1911-11e9-964e-a129a4e77a28.png">
If your curious, check out how [Shopify Polaris](https://polaris.shopify.com/) is using svg links.

**Comment by emmenko** [comment]
Closing this, as we decided not to proceed with this for now.
