### ISSUE TITLE
UIKit i18n messages

### ISSUE THREAD

**Issue by qmateub** [commercetools/ui-kit#46]
**Description**
I was looking for how we handle i18n messages in UI-Kit, but apparently there is no thing related yet but a command that does not work `yarn i18n:build`.

However I have some doubts regarding this.

* Is the UIKit intended to have an i18n folder? If that's the case, should we use the same Transifex project as the MC-FE?
* If we finally go ahead with this, should we just copy the scripts that we have for the FE here?

**Additional context**
I'm asking all of this because one of the points of the last UX/UAT review on channels was that the messages from LocalizedInputs (expand languages, hide languages) are not in transifex. So we have the whole view in DE except those two (we are using there LocalizedInput, MultiLineLocalizedInput)

**Comment by qmateub** [comment]
You mean, in the `core.json` of the MC-FE @montezume 🤔 

When we discussed this? Because TBH I don't remember talking or reading about this 😅 . Maybe I've missed that!

**Comment by emmenko** [comment]
The `i18n:build` script should work. What problem do you have?

**Comment by montezume** [comment]
I think he means there is no concept of `pulling` translations. You run build, and then you fill them in yourself?

**Comment by qmateub** [comment]
@emmenko 

I'm getting this

```js
$ mc-scripts extract-intl --build-translations --output-path=$(pwd)/i18n 'src/components/**/!(*.spec).js'
/bin/sh: mc-scripts: command not found
```

**Comment by qmateub** [comment]
@montezume and me are looking into this. A PR will come 👍

**Comment by emmenko** [comment]
Ah, apparently the dep got removed. I'll add it again.

**Comment by emmenko** [comment]
> @montezume and me are looking into this. A PR will come 👍

Ok great, thanks!

**Comment by emmenko** [comment]
And besides that, it's like @montezume said about managing translations

**Comment by dferber90** [comment]
Glad it was cleared up :) The extraction tot he own repository is still in progress (although finally settling) and there's a few things that need documentation now. This is one of them for sure. I'll add it to my list.

> I'm asking all of this because one of the points of the last UX/UAT review on channels was that the messages from LocalizedInputs (expand languages, hide languages) are not in transifex. So we have the whole view in DE except those two (we are using there LocalizedInput, MultiLineLocalizedInput)

This is on purpose. There are only a few messages for UI-Kit and we won't bother to set up Transifex to translate these

**Comment by qmateub** [comment]
Thanks for asking and taking care of this so fast guys! 👍

**Comment by mariabarrena** [comment]
> Glad it was cleared up :) The extraction tot he own repository is still in progress (although finally settling) and there's a few things that need documentation now. This is one of them for sure. I'll add it to my list.
> 
> > I'm asking all of this because one of the points of the last UX/UAT review on channels was that the messages from LocalizedInputs (expand languages, hide languages) are not in transifex. So we have the whole view in DE except those two (we are using there LocalizedInput, MultiLineLocalizedInput)
> 
> This is on purpose. There are only a few messages for UI-Kit and we won't bother to set up Transifex to translate these

Would be possible to have a list of all the messages that are not into transifex maybe in a special section into the UIkit page? We now need to add Spanish translations for those, but in the upcoming months we will have a couple of more languages so it would be ideal that we send that list to the translations while they are still working on it. :)

**Comment by montezume** [comment]
@mariabarrena they can be accessed currently [here](https://github.com/commercetools/ui-kit/blob/master/i18n/core.json). We could also make a script to generate a more "friendly" list and have that published in a README or something. 🤷‍♂️  Any thoughts?

**Comment by tdeekens** [comment]
Maybe that JSON is good enough? If they grow too much (which we don't expect but are happy to be proven wrong) we can also setup so that they're pushed to transifex.

**Comment by mariabarrena** [comment]
@montezume I can translate from that, but we will definitely need a more friendly list whenever we have the next language to be translated. Let's not worry about it for now :)
Once I'm done with the Spanish translations, who can help me with bringing them to the UIkit?

**Comment by montezume** [comment]
@mariabarrena Sure. If it's today or tomorrow, you can ping me and I would be happy to do it. I'm off the rest of the week though. Otherwise just ask here, I'm sure someone can help 😉

**Comment by montezume** [comment]
@tdeekens Maybe we could incorporate them into storybook some how?

**Comment by mariabarrena** [comment]
No worries @montezume I'm also off from tomorrow on and the translations are available for CT email addresses only. Let's do it next week. I'll name you in the jira ticket so I don't forget anyway :P
