### ISSUE TITLE
[Breaking] - Remove mediaQueries from ui-kit

### ISSUE THREAD

**Issue by montezume** [commercetools/ui-kit#477]
Since the custom media queries defined [here](https://github.com/commercetools/ui-kit/blob/0d333818eb9fa80543f7cb4683b980a53b70e80f/materials/media-queries.mod.css) aren't used in the UI-Kit, they should be moved to the `merchant-center-application-kit`.

**Comment by montezume** [comment]
@emmenko I was thinking we could move them to the (currently unnamed) new app kit package that will house more core components? Maybe we could call it

```@commercetools-frontend/ui``` ?

**Comment by emmenko** [comment]
I would call it `@commercetools-frontend/application-ui-components` or something like this

**Comment by tdeekens** [comment]
Yeah application components is good. We also have some `from-core` stuff if I remember correctly. Not sure we could move that there too.

**Comment by emmenko** [comment]
We'll do that eventually yes. We should make a priority list maybe of what we want to migrate first.
