### ISSUE TITLE
MoneyInput incorrectly parse value when the currency has no fraction digits

### ISSUE THREAD

**Issue by islam3zzat** [commercetools/ui-kit#538]
**Describe the bug**
When having currency that doesn't have fraction digits, and amount greater than thousand.
the entered value is formatted with separator
e.g `100000.00` to `100,000`
but then this separator is treated as fraction symbol (`100.000`), and the value will be considered just `100`

**Expected behavior**
Should parse values like 
```js
{
  amount: "100,000",
  currencyCode: "JPY"
}
```

as 
```js
{
  "type":"centPrecision",
  "currencyCode":"JPY",
  "centAmount": 100000,
  "fractionDigits":0
}
```

**Screenshots**
![kapture 2019-02-14 at 14 40 07](https://user-images.githubusercontent.com/7680511/52790434-d5023580-3066-11e9-834b-f75b2259978a.gif)

**Comment by islam3zzat** [comment]
https://github.com/commercetools/ui-kit/blob/87a24387e49b829ba8838771330cb7fc96c405ba/src/components/inputs/money-input/money-input.js#L290

https://github.com/commercetools/ui-kit/blob/87a24387e49b829ba8838771330cb7fc96c405ba/src/components/inputs/money-input/money-input.js#L341

It is hard for the previous static methods to return correct value without knowledge of the used locale
for example the value `{
  amount: "12,500",
  currencyCode: "JPY"
}` this one's currency is `JPY` which doesn't have fraction digits
The previous functions use this function  
https://github.com/commercetools/ui-kit/blob/87a24387e49b829ba8838771330cb7fc96c405ba/src/components/inputs/money-input/money-input.js#L162

Which does too much work
> // Parsing
// Since most users are not careful about how they enter values, we will parse
// both `.` and `,` as decimal separators.
// When a value is `1.000,00` we parse it as `1000`.
// When a value is `1,000.00` we also parse it as `1000`.

but unfortunately when the currency has no fraction digits, should the value `12,555` be parsed to 
1. `12555` (en locale) or 
2. `12.555` (de locale) 

When calling `MoneyInput.convertToMoneyValue('12,555', 'de') ` ?
if it was 1 it'll be `centPrecision`
```
{
  "type":"centPrecision",
  "currencyCode":"JPY",
  "centAmount": 12555,
  "fractionDigits":0
}
```
if it was *2* it'll be `highPrecision`
```
 {
  "centAmount": 13,
  "currencyCode": "JPY",
  "fractionDigits": 3,
  "preciseAmount": 12555,
  "type": "highPrecision"
 }
```
### Another approach would  to let the user explicitly pass the locale
`MoneyInput.convertToMoneyValue('12,555', 'de') ` 
now we are sure that the output should be
```
 {
  "centAmount": 13,
  "currencyCode": "JPY",
  "fractionDigits": 3,
  "preciseAmount": 12555,
  "type": "highPrecision"
 }
```

**Comment by tdeekens** [comment]
> ### Another approach would to let the user explicitly pass the locale

Maybe we can call that `localeHint` cause it hints the function as in a specific case we know its default heuristics will not work.
