### ISSUE TITLE
Add "Show/Hide" toggle button to Password input

### ISSUE THREAD

**Issue by jonnybel** [commercetools/ui-kit#551]
**Idea**
The Password field could have an extra button to control the `isPasswordVisible` prop.

**Proposed Solution**
This button would be displayed similar to the badge, but would stay inline with the Label and control the visibility of the password inside the component, as a toggle.

Example of the intended design:
![image](https://user-images.githubusercontent.com/2941328/52956055-90400c80-338e-11e9-9f18-d463d7654aed.png)

**Alternatives that have been discussed**
It has been discussed wether the `badge` prop should be used for this, but the UI is slightly different (it's not inline) and this use case may be sufficiently relevant for the Password field to have this special prop.

**Comment by tdeekens** [comment]
Sounds good to me. Initially we liked the idea that all fields have the same API (props). Maybe the `PasswordField` is our first candidate not to (or we deprecate badges in the future anyway).

Couple of thoughts:

1. Should the `PasswordField` with `isPasswordVisible` be controlled with that state of uncontrolled
   - It could manage that state internally and have the the button "show" toggle it
2. Should the ability for a `badge` be removed entirely from `PasswordField`

**Comment by emmenko** [comment]
The badges will be deprecated in the future for all fields (based also on feedback from design). So I would just leave it there for now and we will deprecate/remove them all at once

**Comment by jonnybel** [comment]
The `PasswordField` already has a different API: it's the only one with the `isPasswordVisible` prop.

But I think we could drop the `isPasswordVisible` prop if we manage the state internally according to the button. It would become easier to use.

Instead of it, the only different prop would be an object with the two strings for the text of the On/Off states.

**Comment by tdeekens** [comment]
> But I think we could drop the `isPasswordVisible` prop

Agreed. Managing this state internally makes sense. We only have to make sure that we will not have a case where we need the state to be controlled. That's down to design to reason about.

> The badges will be deprecated in the future for all fields (based also on feedback from design)

Okay, well that surprises me given that we don't have them for too long. But well.

> Instead of it, the only different prop would be an object with the two strings for the text of the On/Off

Do we really need that? Couldn't it be an internal message to UIKit? Do we ever want to change the labels on that actually from the outside. One could argue that's a potential source of inconsistencies even.

> The `PasswordField` already has a different API: it's the only one with the `isPasswordVisible` prop.

Yeah, you're right about it.

**Comment by jonnybel** [comment]
> Do we really need that? Couldn't it be an internal message to UIKit? Do we ever want to change the labels on that actually from the outside. One could argue that's a potential source of inconsistencies even.

I was thinking about translations, but I'm now aware that the UIKit already has a better way to deal with that, so no need for such a prop!
