### ISSUE TITLE
[Idea] Codesandbox template to be used when reporting issues

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#589]
I just noticed while opening an issue #588 that the linked codesandbox was not working due to outdated dependencies.

I'm wondering if we can have some sort of easier way to keep the sandbox up-to-date.

For example, there is an option to connect the repository to the codesandbox, which will keep in sync with the repository changes.
We can then have a folder with e.g. a codesandbox setup that people can just pick up, fork and modify.

Not sure if it's a good idea or if there are other solutions.

**Comment by amine-benselim** [comment]
the codesandbox link in that issue is working for me now. did you update it ?

**Comment by emmenko** [comment]
Yes I did. The one I'm talking about is in the issue template, when you open a new issue.

**Comment by jonnybel** [comment]
Can we consider this solved by https://github.com/commercetools/ui-kit/pull/1378?

I set the Codesandbox to use the `latest` ui-kit version.
