### ISSUE TITLE
[Idea] Allow Text components to accept an intl message

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#637]
**Is your feature request related to a problem? Please describe.**
At the moment, we usually wrap the intl messages (e.g. `FormattedMessage`) with the `Text` components.

```js
<Text.Body>
  <FormattedMessage {...messages.title} />
</Text.Body>
```

**Describe the solution you'd like**
Allow to pass the intl message directly to the `Text` component to avoid the wrapping

```js
<Text.Body intlMessage={messages.title} />

// the prop can also be named differently, e.g. `message` but we should probably make it explicit that it relates to react-intl
```

**Comment by tdeekens** [comment]
Q: this prop could be only used with a "react-intl"-compatible library, correct? As the message itself is expected to have the right shape?

**Comment by emmenko** [comment]
Well yes, but the ui-kit alredy relies on react-intl right?

**Comment by tdeekens** [comment]
It was not meant as criticism in disguise. Sorry if it came across that way. Just to recap that the `message` prop of text components will then "bind to" react-intl.

**Comment by emmenko** [comment]
Ah sorry yeah, it would make sense to "bind it" to react-intl I suppose yes

**Comment by tdeekens** [comment]
Do we actually have to spead it in? Can't we

```js
<Text.Body message={messages.title} />
```

and then the `Text.Body` internally does the

```js
<div>
  <FormattedMessage message={...props.message} />
</div>
```

? 😕

**Comment by emmenko** [comment]
Yes sorry my bad copy/paste, we don't spread it. I'll update the example

**Comment by montezume** [comment]
Sounds like a reasonable request 👍 

I suggest though that we allow users to (optionally) override how the intl message is rendered, so that they could use different intl libraries.
