### ISSUE TITLE
Button components inconsistent and not properly accessible

### ISSUE THREAD

**Issue by jonnybel** [commercetools/ui-kit#642]
## Summary of the Problem 
The button components are showing a lot of inconsistencies regarding sizings and hover/focus states.

See here, all the buttons inside the same container and using their default props as much as possible:
![Kapture 2019-04-04 at 17 54 48](https://user-images.githubusercontent.com/2941328/55569975-ce0cb080-5702-11e9-8cc3-1a784edb1a8c.gif)
(https://codesandbox.io/s/34vv1j1jz6)

Some of them are also not properly accessible in regards of displaying a **focused** and **active** states.
This can be reproduced by trying to navigate through the buttons using the **Tab** key and "clicking" them using the **Space** key (or Enter key for the LinkButton because it's an anchor).

### List of the Identified Problems
- Some buttons fill the available space differently within the same container.
- `SecondaryButton` has an area where the cursor becomes `pointer` that differs from the actual area of the button.
- Only `PrimaryButton` and `LinkButton` display any kind of visual feedback when where are focused or clicked through the keyboard (tab and space keys). All the remaining buttons are **not** accessible.
  - `SecondaryButton` actually becomes accessible when it has its `linkTo` prop is defined, because it becomes wrapped within an `<a>` which is natively accessible on all browsers.
- `SecondaryIconButton` still changes the cursor to `pointer` on hover even when disabled, whereas all the other buttons do not.

**Comment by emmenko** [comment]
Thanks for bringing this up again! How do we wish to proceed here? Should we have a discussion with design first or is it something that we can fix on our own?

**Comment by tdeekens** [comment]
Personally, I would actually call in a meeting with them to generally raise awareness for these kind of accessiblity concerns so that they're incorporated in any future elemment and can be strategically adressed in existing ones (from important to less important elements).

**Comment by montezume** [comment]
@jonnybel have you taken a look at this similar issue?

https://github.com/commercetools/ui-kit/issues/29

**Comment by jonnybel** [comment]
There's a few things I'd like to know if they were design decisions like, for instance, the removal of `outline` on all buttons, which was the native way of providing visual feedback of focused elements, [and removing it is a bad practice](https://a11yproject.com/posts/never-remove-css-outlines/).

Some of bugs we can tackle on our own, but the way to approach them can be very different if wether we want to make breaking changes or not.

To solve the API inconsistencies, the approach proposed in #29 is close to what I had in mind if we would commit to making breaking changes.

**For now,**
I think we could tackle some of the more immediate bugs like the stretching and the weird hovering behaviour on the secondary button, as well as improving their a11y. All of this without any breaking changes.
Then later, given enough time, I'd like to have an attempt at designing a new button API which we could then discuss, and if implemented could coexist during a couple of versions or so with the original API.

**Comment by emmenko** [comment]
@jonnybel should we close this or is this still relevant?

**Comment by jonnybel** [comment]
@emmenko All the listed consistencies have been fixed, and we also have an exported `AccessibleButton` which is the base for the rest of the buttons, so yes I think we can close this now.
