### ISSUE TITLE
Styling bug when applying `isReadOnly` to inputs

### ISSUE THREAD

**Issue by qmateub** [commercetools/ui-kit#695]
**Describe the bug**
Some of the inputs in UIKit are not applying correctly the `isReadOnly` style when the prop is defined. This is a little bit unfortunate because according the the docs of each input, all of them accept the prop.

**To Reproduce**
Just create a test view and define all of the inputs with `isReadOnlyProp` to true. This is the list of the status for each input.

* AsyncCreatableSelectInput  ✅
* AsyncSelectInput  ✅
* CheckboxInput ✅
* CreatableSelectInput  ✅
* DateInput ✅
* DateRangeInput ✅
* DateTimeInput ✅
* LocalizedMoneyInput ✅
* LocalizedMultilineTextInput ✅
* LocalizedTextInput ✅
* MoneyInput ✅
* MultilineTextInput ✅
* NumberInput ✅
* PasswordInput ✅
* RadioInput ✅
* SelectInput  ✅
* TextInput ✅
* TimeInput ✅
* ToggleInput ❌

**Expected behavior**
All the inputs should follow the same styling behavior when defining `isReadOnly`

**Screenshots**
![image](https://user-images.githubusercontent.com/11442895/56356932-77ab7180-61da-11e9-8922-75abd9122441.png)

**Additional Notes**
Didn't test if this also affects the Field components that forwards the prop to the inputs 😅

**Comment by montezume** [comment]
Hm, `react-select` doesn't support the 'readonly' prop... I'm not sure if makes sense for selects to be readonly. We will need to talk to design about this...

**Comment by montezume** [comment]
`react-select` doesn't support read-only out of the box. So there's no easy way of making our `SelectInputs` readonly

https://github.com/JedWatson/react-select/issues/1802

**Comment by montezume** [comment]
FYI @qmateub I'm going to keep updating your post as I progress on this 🙃

**Comment by montezume** [comment]
FYI @jonnybel I updated the description to reflect your latest changes in #1192
