### ISSUE TITLE
Ship transpiled code (webpack or rollup)

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#7]

**Comment by emmenko** [comment]
@montezume just to clarify: will you be working on this then?

**Comment by islam3zzat** [comment]
@montezume if you are not working on it, I'd like to do this one

**Comment by montezume** [comment]
I was working on this yesterday, did we decide if we wanted to go with rollup or webpack?

**Comment by emmenko** [comment]
Let's try webpack first

**Comment by montezume** [comment]
@islam3zzat maybe you should take this then? I got most of there way there with [rollup](https://github.com/commercetools/ui-kit/compare/ml-add-rollups?expand=1) but feel like we need to fix more issues to do with dependancies vs peer deps...

**Comment by islam3zzat** [comment]
Too late, will have no time to work on it now :(

**Comment by dferber90** [comment]
I'll open it up again as the Webpack approach wasn't too fruitful (we can't produce a build which supports tree-shaking). Let's give rollup another spin.

@emmenko provided this helpful article around it: https://thedrearlight.com/blog/delivering-js-modules.html

**Comment by emmenko** [comment]
Since it relates to how we produce the bundles, we should probably also talk about the "export" structure.

In general we should have most of the components on the "main" export

```js
import { TextField, IconButton } from '@commercetools-frontend/ui-kit';
```

To avoid polluting the main export namespace, we should also provide additional entry points for other folders. For example:

```js
import uiKitMessages from '@commercetools-frontend/ui-kit/i18n';
import { LogoSVG } from '@commercetools-frontend/ui-kit/images';
import { withMouseDownState } from '@commercetools-frontend/ui-kit/hocs';
import { filterDataAttributes } from '@commercetools-frontend/ui-kit/utils';
import { Spacings, Constraints } from '@commercetools-frontend/ui-kit/materials';

// ...also css modules from materials
```

NOTE: some of them are "just" folders (e.g. `i18n`, `images`), others are transpiled JS bundles (e.g. `hocs`, `utils`) and others are a mix (e.g. `materials`, which contains transpiled JS and CSS files).

I'm not 100% sure this is the "right" approach, but **it feels more natural from the perspective of a library consumer**.

Thoughts?

**Comment by dferber90** [comment]
Unfortunately, I'm not aware of a way to create such a build. I've been playing around with rollup a bit in a side-project and couldn't find a straightforward way to do this.

Of course we could copy some stuff into the resulting folder, but this seems weird. If any of our main exports uses anything from `utils`, and we also copy `utils` to the folder we publish from, then that utility function will exist twice: once in the `utils` folder and once bundled into the main build. This is pretty bad for the bundle size of course.

Another approach would be to use a function as `externals` and to split out the modules. But as we compile to `cjs` and to `esm`, both compilations would end up trying to import the same file from `utils`.

This just doesn't seem to be a well-supported thing. The proper approach is probably to package each thing we want to export into their own module. We could use lerna for this.

```js
import{ PrimaryActionButton } from '@commercetools-frontend/ui-kit';
import uiKitMessages from '@commercetools-frontend/ui-kit-messages';
import { filterDataAttributes } from '@commercetools-frontend/ui-kit-utils';
```

What do you think?

**Comment by emmenko** [comment]
Btw: I was looking at `react-virtualized` setup

https://github.com/bvaughn/react-virtualized/blob/master/package.json#L14-L19

They only bundle with rollup for `umd` target. For `cjs` and `es` they use `babel`.
Also, they use postcss to extract the css.

**Comment by tdeekens** [comment]
I think, hoping to understand things enough, that 

1. Exporting from the top-level module scope (`import { PrimaryButton } from '@commercetools-frontend/uikit`
   - Is hard to achieve in an automated build setup as it seems fragile
   - It's a lot of manual work to `re-export` to the top-level scope. Down from inside the module up
2. Reaching into the package when importing seems natural-ish
   - But essentially gives little control over what the package actually exports
   - You can each in and import almost anything as it's all in `dist`
3. Each module is it's own package in ui-kit being a mono-repo
   - E.g. `@commercetools-frontned/uikit-buttons` is something you'd import `{ PrimaryButton }` from
   - That's not a ton of fun as it's nicer when the package itself would be in it's own npm namespace (e.g. `@ct-uikit` or `@inser-mavel-character`

I think (personally) we could maybe be able to live with 2. (the each in importing) for now and see how it feels to then move on?

**Comment by emmenko** [comment]
The monorepo/component approach might "solve the import problem" but I feel at the same time it creates a new one (if we do it on a component base): imagine how many different deps you would need to import.

Nevertheless, I think we still have the "problem" of the non-js bundles (i18n, images, css modules). Where should we put them and how would you import them?

**Comment by dferber90** [comment]
I sense some confusion, let's talk about it tomorrow :)

**Comment by emmenko** [comment]
Btw: we still have this problem at the moment that `react-virtualized` has some circular dependency when bundled with rollup.

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/1110551/45182763-87b1aa80-b222-11e8-8fab-6f36da68faf7.png">

---

My god, why is it so complicated! 😩

**Comment by emmenko** [comment]
> They only bundle with rollup for `umd` target. For `cjs` and `es` they use `babel`.
Also, they use `postcss` to extract the css.

I looked at other libraries and they simply use babel to compile to cjs and esm. Rollup only for umd.
I would say: let’s keep umd out of the picture for now and simply use babel.

**Comment by tdeekens** [comment]
I think it's okay to assume that UIKit will be consumed by a module loader. So UMD we don't need. CJS is also not really needed as all loaders understand ESM by now. That leaves us with one. Which could mean transpiling with babel could be enough. I guess static files (like CSS) would also just be PostCSS'ed?

**Comment by emmenko** [comment]
Yes exactly 👌

**Comment by emmenko** [comment]
I'll play a bit around with that then.

**Comment by montezume** [comment]
I updated my branch with the same SVG config as we have in webpack. Still having some issues with that circular dep warning. I would like to extract the css as I think it makes more sense but that's just my opinion 🤷‍♂️

**Comment by montezume** [comment]
We can kill both warnings by making `styled-components` and `react-virtualized` peerDeps. One way to fix 👍
