### ISSUE TITLE
Accessibility and `Inputs` (and `Fields`)

### ISSUE THREAD

**Issue by montezume** [commercetools/ui-kit#717]
#### Summary

I'm opening this issue to track the use of our `Inputs` and `Fields` with the keyboard. Generally, users should be able to use our inputs with the keyboard. 

We should go through all of our inputs, and add here how they respond to these "tab" events, and how they look under focus. We should also coordinate with design

cc @franzi-t

**Comment by montezume** [comment]
I went through all of our inputs, and the only one left is the `RadioGroup`. I'll look at refactoring that tomorrow. 👍 

However, how we deal with focus in our "accessible" components isn't great. We should look into another way of focusing the component, instead of just putting it into it's "hovered" state.

**Comment by emmenko** [comment]
@jonnybel I guess this can be closed now?

**Comment by jonnybel** [comment]
Closing this since we recently improved the keyboard accessibility of all of our inputs.
