### ISSUE TITLE
Icons should support theming

### ISSUE THREAD

**Issue by montezume** [commercetools/ui-kit#725]
Icons should support theming 🎈

**Comment by montezume** [comment]
Will be available in `10.0.0` see #726

**Comment by montezume** [comment]
@jonnybel do you think we could also make a codemod for the icon breaking change?

**Comment by jonnybel** [comment]
Yes, the prop name change can be done easily with the codemod we have, just have to add another step to remap the values of the prop with their new names as well.

**Comment by montezume** [comment]
This has been released in v10! 

https://github.com/commercetools/ui-kit/releases/tag/v10.0.0
