### ISSUE TITLE
Workaround react-select not supporting triggering onSubmit when clicking Enter

### ISSUE THREAD

**Issue by ahmehri** [commercetools/ui-kit#751]
**Is your feature request related to a problem? Please describe.**
`react-select` used under the hood in `ui-kit` components, e.g `DateTimeInput`, doesn't support the `onSubmit` method being triggered when clicking `Enter`. As a result, apps using `ui-kit` are implementing a workaround which consists of wrapping the component into a `div`:

```
<div onKeyDown={event => event.key === "Enter" && formikProps.handleSubmit()}>
  <DateTimeInput />
</div>;
```

**Describe the solution you'd like**
Move the workaround to `ui-kit` level, or optimally update `react-select` to a version that supports the desired behaviour, if any.

**Comment by montezume** [comment]
Are you sure you mean `DateTimeInput`? It uses `downshift`, not `react-select` 😕

**Comment by montezume** [comment]
Can you provide an example in plain HTML of what you want the input to do? I don't understand.

**Comment by montezume** [comment]
I'm going to close this. Feel free to re open if it remains a problem and you can provide some additional reproduction instructions.
