### ISSUE TITLE
Cards hide part of the tooltip

### ISSUE THREAD

**Issue by islam3zzat** [commercetools/ui-kit#763]
**Describe the bug**
Cards hide part of the tooltips within a sibling card

**To Reproduce**

1. Go to https://mc-6860.gcp.escemo.com/adnan-nodejs-test-project/products/a6aadb7b-d7cb-4222-834c-017a5aada006/general
2. Click on the edit button next to `With Nested Type: do not delete this`
3. Then hover on the edit button next to `Is a Nested reference: do not delete`
4. you'll notice that part of the tooltip don't show

**Expected behavior**
Both card and the Tooltip should be fully available

**Screenshots**
![image](https://user-images.githubusercontent.com/7680511/57607890-55eca280-756c-11e9-9daa-212e2218eff0.png)

**Comment by montezume** [comment]
Thanks for the easy to reproduce case 👍
