### ISSUE TITLE
Font text of tooltip is transparent?

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#851]
<img width="193" alt="image" src="https://user-images.githubusercontent.com/1110551/59327789-e2fd5580-8cea-11e9-8ddd-80dc7995d595.png">

**Comment by montezume** [comment]
Hi, is this possible a z-index issue? I don't think the text in your screenshot is transparent. Maybe since you are using this inside two levels of modals (which use portals), we need to increase the z-index of the container.

**Comment by emmenko** [comment]
It was z-index issue, thanks!

**Comment by montezume** [comment]
It turned out that we needed to override the `TooltipWrapperComponent` component. See https://github.com/commercetools/merchant-center-application-kit/pull/735 for more details.
