### ISSUE TITLE
Upcoming breaking changes (v10)

### ISSUE THREAD

**Issue by emmenko** [commercetools/ui-kit#859]
In appkit we opened an issue to talk about upcoming breaking changes, mostly around having 1st class support for react hooks.
https://github.com/commercetools/merchant-center-application-kit/issues/748

Since we started already working on a v10 release here, it would be nice to align on the react hooks side of things for the uikit as well.

**Comment by emmenko** [comment]
What are other breaking changes planned for v10?

**Comment by montezume** [comment]
* Icons will lose the `theme` prop, and it will be replaced with a `color` prop.
* Dropping `withMouseOverState` HOC from UI-Kit. (it can be copied into MC)
* Deprecated custom properties will be dropped.

**Comment by jonnybel** [comment]
* The `standard-transition` customProperty no longer animates `all`; The developer should specify what's the `transition-property` to animate.
* `Text` components: Deprecating `elementType` prop of Text.Headline and Text.Subheadline components - replaced with `as` prop. Deprecating `isInline` prop of Text.Body component.
