### ISSUE TITLE
Tooltip docs are not rendered correctly in storybook

### ISSUE THREAD

**Issue by ahmehri** [commercetools/ui-kit#895]
**Describe the bug**
The docs of the `Tooltip` component in storybook are not rendered correctly.

**To Reproduce**

1. Go to https://uikit.commercetools.com/?path=/story/components-tooltips--tooltip
2. Check "Customizing the wrapper" section
3. The example code is not rendered correctly

**Expected behavior**
The docs should be rendered correctly.

**Screenshots**

| Wrong Rendering | Correct Rendering |
| --- | --- |
|<img width="939" alt="Screenshot 2019-06-25 at 17 14 59" src="https://user-images.githubusercontent.com/3668245/60111365-15d52e00-976e-11e9-8282-6eb3cac9eef8.png">|<img width="920" alt="Screenshot 2019-06-25 at 17 15 04" src="https://user-images.githubusercontent.com/3668245/60111371-1968b500-976e-11e9-8cc5-8de893fc298f.png">|

**Comment by montezume** [comment]
Hm... yeah it seems like a bug with `storybook-readme`
