### ISSUE TITLE
`Spacings.Inline` should support `flex-wrap`

### ISSUE THREAD

**Issue by montezume** [commercetools/ui-kit#898]
#### Summary

The `Spacings.Inline` component should support the flex-wrap property.

**Comment by emmenko** [comment]
Can you give a bit more background on the expected outcome with a reproducible example or a screenshot?

I’m not against it, I just want to understand the problem 😄

**Comment by montezume** [comment]
Sure. With flex wrap, we can do something like this.


![flex-wrap](https://user-images.githubusercontent.com/2425013/60268680-40012a00-98ed-11e9-963f-f1e698ded0c6.gif)

**Comment by emmenko** [comment]
I see, and how does it behave without?

**Comment by montezume** [comment]
![npwrap](https://user-images.githubusercontent.com/2425013/60268894-c1f15300-98ed-11e9-9568-2f3f778ac1c6.gif)

**Comment by emmenko** [comment]
Thanks!
