### ISSUE TITLE
TextInput onKeyPress event hook

### ISSUE THREAD

**Issue by davidweterings** [commercetools/ui-kit#909]
**Is your feature request related to a problem? Please describe.**
We're currently building custom Merchant Center applications using components from this library. One of the things we're trying to implement is a search input field. We'd like to use `TextInput`, but we don't want to search on every `onChange` event, but only when the user presses a key (in this case Enter).

**Describe the solution you'd like**
Add an optional hook for `onKeyPress` to the `TextInput` component.

**Describe alternatives you've considered**
Create our own input component with the correct styling.

**Additional context**
I'm not the most experienced React developer, so perhaps I missed a way to accomplish this with the existing components.

**Comment by tdeekens** [comment]
Doesn't the `TextInput`'s `onChange` emit the `event`. So something like `onChange={event => event.key === 'Enter' && props.onEnter(event)}` would do the trick?

**Comment by emmenko** [comment]
The `onChange` event does not trigger on certain keys, so for enter you need to use "key handlers".

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/1110551/60514403-b5983c00-9cd9-11e9-98f2-339bb9480485.png">

**Comment by emmenko** [comment]
@davidweterings thanks for reaching out to us! We'll evaluate your request and get back to you.

**Comment by montezume** [comment]
Hi,

Thanks for creating the issue. Have you considered just wrapping your input in a form for now? I created a [codesandbox](https://codesandbox.io/s/nervous-rain-f8jd2) to show this. This way you don't need to use onKeyPress and watch for a specific key press.

Does this solve your problem?

Sidenote: this issue goes well with #706. Once we do this refactor, you would be able to pass any props you need to the input itself.

**Comment by davidweterings** [comment]
Thanks for the suggestion @montezume . We actually implemented it exactly like this just a few moments ago! 

Since there's already a ticket for passing the other props, I'm gonna close this one. Thanks again for the quick response!
