### ISSUE TITLE
No keys for MC dashboard Calendar

### ISSUE THREAD

**Issue by mariamlomia** [commercetools/ui-kit#917]
**No keys for MC dashboard Calendar**

Calendar section of MC Dashboard cannot be translated because we don't have corresponding strings for them in Transifex. 

**I am not sure what the process of adding keys to TX is, so if anyone could help me I'd appreciate that**

**Screenshots**
<img width="1059" alt="dashboard dropdown calendar" src="https://user-images.githubusercontent.com/52162528/60705296-0c368d80-9f07-11e9-918c-97a61a6a59d7.png">

**Comment by emmenko** [comment]
Thanks for reporting this issue. Those strings are generated from the `moment` library, they are not "normal" translations.

https://github.com/commercetools/ui-kit/blob/7c10674e715bf93f6a6c3c6bd94e6eab185d113c/src/utils/calendar-time.js#L68-L72

Maybe there is not data for the specified locale? @montezume can you look into it?

**Comment by montezume** [comment]
Thanks, this looks like a bug! I'll check it out
